package com.spanishapp.ui.games

/**
 * Frase Loca — банк A2 (уровни 26–50, темы 6–10).
 * Ядро тем — главные A2-провалы русскоязычных: Indefinido vs Imperfecto,
 * Pretérito Perfecto (hoy/esta semana → perfecto в Испании), futuro.
 */
internal object FraseLocaBankA2 {

    private val AYER = FraseTheme(
        id = "ayer",
        title = "Вчерашний день · Indefinido",
        cefr = "A2",
        phrases = listOf(
            flp("Я ничего не сказал.", "No dije nada.",
                flt("decí", "Decir — неправильный глагол: dije")),
            flp("Она родилась в Севилье.", "Ella nació en Sevilla.",
                flt("nacía", "Рождение — точечное событие: Indefinido nació")),
            flp("Пабло совершил ошибку.", "Pablo cometió un error.",
                flt("hizo", "«Совершить ошибку» = cometer un error, не hacer")),
            flp("Вдруг зазвонил телефон.", "De repente sonó el teléfono.",
                flt("sonaba", "«Вдруг» — завершённое событие: Indefinido sonó")),
            flp("Вчера я купил красную машину.", "Ayer compré un coche rojo.",
                flt("compraba", "Завершённое действие с ayer — Indefinido: compré"),
                flt("roja", "Coche — мужской род: rojo")),
            flp("Мы посмотрели очень хороший фильм.", "Vimos una película muy buena.",
                flt("Veíamos", "Один завершённый просмотр — Indefinido: vimos"),
                flt("bueno.", "Película — женский род: buenA")),
            flp("Что ты делал вчера вечером?", "¿Qué hiciste ayer por la noche?",
                flt("haciste", "Hacer — неправильный: hiciste, без «а»")),
            flp("Ана вчера не пришла на занятие.", "Ana no vino ayer a clase.",
                flt("venía", "Конкретный вчерашний факт — Indefinido: vino")),
            flp("В субботу мы поужинали в ресторане.", "El sábado cenamos en un restaurante.",
                flt("cenábamos", "Один конкретный ужин — Indefinido: cenamos")),
            flp("В прошлом году мы съездили в Барселону.", "El año pasado fuimos a Barcelona.",
                flt("íbamos", "Одна завершённая поездка — Indefinido: fuimos"),
                flt("en", "Направление — ir A Barcelona")),
            flp("Я проснулся в семь и принял душ.", "Me desperté a las siete y me duché.",
                flt("despertaba", "Цепочка событий утра — Indefinido: desperté"),
                flt("duchaba.", "И душ — тоже событие: me duché")),
            flp("Они переехали в Мадрид в двухтысячном году.", "Se mudaron a Madrid en el año dos mil.",
                flt("mudaban", "Переезд — точечное событие: se mudaron"),
                flt("al", "В таком-то году = EN el año")),
        )
    )

    private val ANTES = FraseTheme(
        id = "antes",
        title = "Раньше и в детстве · Imperfecto",
        cefr = "A2",
        phrases = listOf(
            flp("Раньше не было интернета.", "Antes no había internet.",
                flt("hubo", "Фон «раньше» — Imperfecto: había")),
            flp("Моя бабушка готовила очень вкусно.", "Mi abuela cocinaba muy bien.",
                flt("cocinó", "Привычка в прошлом — Imperfecto: cocinaba")),
            flp("Раньше я жил в маленькой деревне.", "Antes vivía en un pueblo pequeño.",
                flt("viví", "«Раньше» — привычное прошлое: vivía")),
            flp("В детстве я много играл на улице.", "De niño jugaba mucho en la calle.",
                flt("jugé", "Форма jugaba; а в Indefinido было бы juGUÉ, с u")),
            flp("Каждое лето мы ездили на пляж.", "Todos los veranos íbamos a la playa.",
                flt("fuimos", "«Каждое лето» — привычка: Imperfecto íbamos")),
            flp("Я читал, когда вошла Мария.", "Leía cuando entró María.",
                flt("Leí", "Фоновое действие — Imperfecto: leía"),
                flt("entraba", "Прервавшее событие — Indefinido: entró")),
            flp("Она была уставшей и хотела спать.", "Estaba cansada y quería dormir.",
                flt("Era", "Состояние усталости — ESTAR: estaba"),
                flt("quiso", "Фон желания — Imperfecto: quería")),
            flp("Я не знал, что ты здесь.", "No sabía que estabas aquí.",
                flt("supe", "Sabía = знал (фон). Supe = УЗНАЛ (момент)"),
                flt("estás", "Согласование времён: estabas")),
            flp("Было восемь вечера, когда он позвонил.", "Eran las ocho cuando llamó.",
                flt("Fueron", "Время суток в прошлом — Imperfecto: eran"),
                flt("llamaba.", "Звонок — точечное событие: llamó")),
            flp("Когда я был маленьким, у меня была собака.", "Cuando era pequeño, tenía un perro.",
                flt("fui", "Возраст/этап жизни — Imperfecto: era"),
                flt("tuve", "Фон обладания — Imperfecto: tenía")),
            flp("В юности он хотел стать художником.", "De joven quería ser pintor.",
                flt("quiso", "Фон желания — Imperfecto: quería"),
                flt("estar", "Кем стать/быть по профессии — SER")),
            flp("Пока мама готовила, я накрывал на стол.", "Mientras mamá cocinaba, yo ponía la mesa.",
                flt("cocinó,", "Mientras — два параллельных фона: Imperfecto"),
                flt("puse", "Накрывал (параллельно) — Imperfecto: ponía")),
        )
    )

    private val TRABAJO = FraseTheme(
        id = "trabajo",
        title = "Работа и учёба · Perfecto",
        cefr = "A2",
        phrases = listOf(
            flp("Сегодня я работал восемь часов.", "Hoy he trabajado ocho horas.",
                flt("trabajé", "Hoy — незакрытый период: Perfecto he trabajado")),
            flp("В этом году я многому научился.", "Este año he aprendido mucho.",
                flt("aprendí", "Este año — период ещё идёт: Perfecto")),
            flp("Ты уже закончил отчёт?", "¿Ya has terminado el informe?",
                flt("terminaste", "Ya + сегодняшний контекст — Perfecto: has terminado")),
            flp("Я ещё не говорил с шефом.", "Todavía no he hablado con el jefe.",
                flt("hablé", "Todavía no — Perfecto: no he hablado")),
            flp("Мария только что вышла из офиса.", "María acaba de salir de la oficina.",
                flt("salido", "Acabar de + ИНФИНИТИВ: acaba de salir")),
            flp("Я написал два письма этим утром.", "He escrito dos cartas esta mañana.",
                flt("escribido", "Escribir — неправильное причастие: escrito")),
            flp("Мы ещё не видели новый проект.", "Todavía no hemos visto el proyecto nuevo.",
                flt("veído", "Ver — неправильное причастие: visto")),
            flp("Ты когда-нибудь работал за границей?", "¿Alguna vez has trabajado en el extranjero?",
                flt("trabajaste", "Alguna vez (опыт жизни) — Perfecto")),
            flp("На этой неделе у нас было много собраний.", "Esta semana hemos tenido muchas reuniones.",
                flt("tuvimos", "Esta semana — период ещё идёт: Perfecto"),
                flt("muchos", "Reuniones — женский род: muchAs")),
            flp("Сегодняшнее собрание было очень длинным.", "La reunión de hoy ha sido muy larga.",
                flt("estado", "Характеристика собрания — SER: ha sido"),
                flt("largo.", "Reunión — женский род: largA")),
            flp("Он никогда не опаздывал на работу.", "Nunca ha llegado tarde al trabajo.",
                flt("llegando", "После haber — причастие: llegado")),
            flp("Мы уже отправили все документы клиенту.", "Ya hemos enviado todos los documentos al cliente.",
                flt("enviamos", "Ya (к настоящему моменту) — Perfecto: hemos enviado"),
                flt("todas", "Documentos — мужской род: todOs")),
        )
    )

    private val PLANES = FraseTheme(
        id = "planes",
        title = "Планы и будущее",
        cefr = "A2",
        phrases = listOf(
            flp("Я позвоню тебе вечером.", "Te llamaré por la noche.",
                flt("en", "«Вечером» = por la noche")),
            flp("Завтра я буду учить испанский.", "Mañana voy a estudiar español.",
                flt("estudio", "План = ir a + инфинитив: voy a estudiar")),
            flp("Что ты будешь делать летом?", "¿Qué harás en verano?",
                flt("hacerás", "Hacer — неправильная основа будущего: haré, harás")),
            flp("Скоро всё будет хорошо.", "Pronto todo estará bien.",
                flt("será", "Состояние/самочувствие — ESTAR: estará bien")),
            flp("На выходных мы поедем за город.", "El fin de semana iremos al campo.",
                flt("En", "El fin de semana — без предлога en")),
            flp("Когда-нибудь я буду свободно говорить по-испански.", "Algún día hablaré español con fluidez.",
                flt("hablará", "«Я» — окончание -é: hablaré")),
            flp("Наверное, придёт много народу.", "Seguramente vendrá mucha gente.",
                flt("venirá", "Venir — неправильная основа: vendrá"),
                flt("muchas", "Gente — единственное число: mucha gente")),
            flp("Если будет солнечно, пойдём на пляж.", "Si hace sol, iremos a la playa.",
                flt("hará", "После SI — настоящее время: si hace sol"),
                flt("en", "Направление — a la playa")),
            flp("Мы собираемся снять квартиру в центре.", "Vamos a alquilar un piso en el centro.",
                flt("alquilamos", "Ir a + инфинитив: vamos a alquilar"),
                flt("una", "Piso — мужской род: un piso")),
            flp("Я позвоню тебе, как только приеду.", "Te llamaré en cuanto llegue.",
                flt("llegaré", "После en cuanto (о будущем) — subjuntivo: llegue")),
            flp("Через два года он закончит университет.", "Dentro de dos años terminará la universidad.",
                flt("terminaré", "«Он» — окончание -á: terminará")),
            flp("Обещаю, что больше не буду опаздывать.", "Prometo que no volveré a llegar tarde.",
                flt("de", "«Снова сделать» = volver A + инфинитив"),
                flt("llegaré", "После volveré a — инфинитив: llegar")),
        )
    )

    private val VIAJES = FraseTheme(
        id = "viajes",
        title = "Путешествия",
        cefr = "A2",
        phrases = listOf(
            flp("Во сколько вылетает самолёт?", "¿A qué hora sale el avión?",
                flt("En", "«Во сколько» = ¿A qué hora?"),
                flt("la", "Avión — мужской род: el avión")),
            flp("Чемодан весит двадцать кило.", "La maleta pesa veinte kilos.",
                flt("El", "Maleta — женский род: la maleta"),
                flt("pesan", "La maleta — единственное число: pesA")),
            flp("Мне нужны паспорт и виза.", "Necesito el pasaporte y el visado.",
                flt("la", "В Испании виза — EL visado (м.р.)")),
            flp("Где можно поменять деньги?", "¿Dónde se puede cambiar dinero?",
                flt("puedes", "Безличное «можно» = se puede")),
            flp("Не забудь солнцезащитный крем!", "¡No olvides la crema solar!",
                flt("olvidas", "Запрет = no + subjuntivo: no olvides"),
                flt("el", "Crema — женский род: la crema")),
            flp("Мы только что забронировали отель у моря.", "Acabamos de reservar un hotel junto al mar.",
                flt("reservado", "Acabar de + ИНФИНИТИВ: reservar")),
            flp("Мы заблудились в старом городе.", "Nos hemos perdido en el casco antiguo.",
                flt("perdidos", "Причастие с haber не согласуется: perdido")),
            flp("Сколько длится полёт до Малаги?", "¿Cuánto dura el vuelo a Málaga?",
                flt("Cuántos", "«Сколько длится» = cuánto dura")),
            flp("Нам понравилась экскурсия по центру.", "Nos gustó la visita por el centro.",
                flt("gustamos", "Gustar «наоборот»: nos gustÓ la visita"),
                flt("gustaron", "La visita — единственное число: gustó")),
            flp("Этот пляж — самый красивый на острове.", "Esta playa es la más bonita de la isla.",
                flt("el", "Playa — женский род: la más bonita"),
                flt("en", "Самый красивый НА острове = DE la isla")),
            flp("Я загорал на пляже всё утро.", "Tomé el sol en la playa toda la mañana.",
                flt("tomaba", "Весь отрезок целиком (toda la mañana) — Indefinido"),
                flt("todo", "Mañana — женский род: todA la mañana")),
            flp("Поезд в Толедо отправляется с восьмого пути.", "El tren a Toledo sale del andén ocho.",
                flt("de", "de + el = DEL: del andén"),
                flt("anden", "Не теряй тильду: andén")),
        )
    )

    val themes: List<FraseTheme> = listOf(AYER, ANTES, TRABAJO, PLANES, VIAJES)
}
