package com.spanishapp.ui.games

/**
 * Frase Loca — банк B2 (уровни 76–100, темы 16–20).
 * Ядро: Subjuntivo Imperfecto / условные периоды, пассив и перифразы,
 * формальный регистр (уроки u15), идиомы, культура Испании.
 */
internal object FraseLocaBankB2 {

    private val SUBJUNTIVO2 = FraseTheme(
        id = "subjuntivo2",
        title = "Прошедший Subjuntivo и условия",
        cefr = "B2",
        phrases = listOf(
            flp("Что бы ни случилось, я тебя поддержу.", "Pase lo que pase, te apoyaré.",
                flt("Pasa", "Устойчивая формула: PASE lo que pase"),
                flt("apoyara.", "Главная часть — будущее: apoyaré")),
            flp("Жаль, что тебя там не было!", "¡Ojalá hubieras estado allí!",
                flt("estabas", "Ojalá о прошлом — hubieras estado"),
                flt("estuvieras", "Сожаление о прошлом: hubieras + причастие")),
            flp("Он говорил так, будто всё знал.", "Hablaba como si lo supiera todo.",
                flt("sabía", "Como si — subjuntivo imperfecto: supiera"),
                flt("sepa", "Como si не бывает с presente: supiera")),
            flp("Я боялся, что уже слишком поздно.", "Temía que fuera demasiado tarde.",
                flt("era", "Temía que — subjuntivo: fuera"),
                flt("sea", "Сдвиг в прошлое: fuera")),
            flp("Я хотел, чтобы ты был здесь.", "Quería que estuvieras aquí.",
                flt("estabas", "Quería que — subjuntivo: estuvieras"),
                flt("estés", "Сдвиг в прошлое: estés → estuvieras")),
            flp("Не было никого, кто мог бы мне помочь.", "No había nadie que pudiera ayudarme.",
                flt("podía", "Nadie que — subjuntivo: pudiera"),
                flt("pueda", "Сдвиг в прошлое: pudiera")),
            flp("Было бы лучше, если бы ты помолчал.", "Sería mejor que te callaras.",
                flt("callas.", "Sería mejor que — subjuntivo imperfecto: callaras"),
                flt("calles.", "Condicional в главной — imperfecto de subj. в que")),
            flp("Я искал работу, которая позволяла бы путешествовать.", "Buscaba un trabajo que me permitiera viajar.",
                flt("permitía", "Неопределённая работа — subjuntivo: permitiera"),
                flt("permita", "Сдвиг в прошлое: permitiera")),
            flp("Мне бы хотелось, чтобы мы виделись чаще.", "Me gustaría que nos viéramos más a menudo.",
                flt("vemos", "Gustaría que — subjuntivo imperfecto: viéramos"),
                flt("veamos", "После gustaría — сдвиг: viéramos")),
            flp("Даже если бы он попросил, я бы не согласился.", "Aunque me lo pidiera, no aceptaría.",
                flt("pediría", "Aunque + гипотеза — subjuntivo: pidiera"),
                flt("aceptara.", "Главная часть — condicional: aceptaría")),
            flp("Если бы я был богат, я бы купил дом на пляже.", "Si fuera rico, compraría una casa en la playa.",
                flt("sería", "После SI — subjuntivo: fuera"),
                flt("compraba", "Главная часть — condicional: compraría"),
                flt("un", "Casa — женский род: una")),
            flp("Если бы ты пришёл вчера, ты бы увидел Ану.", "Si hubieras venido ayer, habrías visto a Ana.",
                flt("vendrías", "Третий тип условия: si hubieras venido"),
                flt("veído", "Ver — неправильное причастие: visto"),
                flt("habías", "Итог-гипотеза: habrías (condicional compuesto)")),
        )
    )

    private val PASIVA = FraseTheme(
        id = "pasiva",
        title = "Пассив и перифразы",
        cefr = "B2",
        phrases = listOf(
            flp("Здесь говорят по-английски.", "Aquí se habla inglés.",
                flt("hablan", "Безличное se + ед.ч.: se habla inglés")),
            flp("Ужин уже подан.", "La cena ya está servida.",
                flt("es", "Результат-состояние — ESTAR: está servida"),
                flt("servido.", "Cena — женский род: servidA")),
            flp("Только что объявили результаты.", "Acaban de anunciar los resultados.",
                flt("anunciado", "Acabar de + ИНФИНИТИВ: anunciar"),
                flt("a", "Acabar DE, не acabar a")),
            flp("Магазины закрываются в восемь.", "Las tiendas se cierran a las ocho.",
                flt("cierra", "Las tiendas — множественное: se cierraN")),
            flp("Он продолжает работать в той же компании.", "Sigue trabajando en la misma empresa.",
                flt("trabajar", "Seguir + ГЕРУНДИЙ: sigue trabajando"),
                flt("mismo", "Empresa — женский род: la mismA")),
            flp("Мы снова увиделись через десять лет.", "Volvimos a vernos diez años después.",
                flt("de", "«Снова» = volver A + инфинитив")),
            flp("Становится поздно, нам пора идти.", "Se está haciendo tarde, tenemos que irnos.",
                flt("hacer", "Процесс — estar + герундий: haciendo"),
                flt("ir.", "«Уходить» = irSE: irnos")),
            flp("Я только начал читать эту книгу.", "Acabo de empezar a leer este libro.",
                flt("empiezo", "Acabar de + инфинитив: empezar"),
                flt("esta", "Libro — мужской род: este")),
            flp("Дом был построен в тысяча девятисотом году.", "La casa fue construida en mil novecientos.",
                flt("construido", "Casa — женский род: construidA"),
                flt("era", "Пассив события — fue + причастие")),
            flp("Этот роман был написан Сервантесом.", "Esta novela fue escrita por Cervantes.",
                flt("escrito", "Novela — женский род: escritA"),
                flt("de", "Автор в пассиве = POR Cervantes")),
            flp("Проблема ещё не решена.", "El problema todavía no está resuelto.",
                flt("La", "Problema — мужской род (греческое -ma): EL problema"),
                flt("resolvido.", "Resolver — неправильное причастие: resuelto"),
                flt("es", "Состояние-результат — ESTAR")),
            flp("Эту песню этим летом слушают повсюду.", "Esta canción se escucha por todas partes este verano.",
                flt("escuchan", "Se + ед.ч. (la canción): se escucha"),
                flt("todos", "Partes — женский род: todAs partes")),
        )
    )

    private val FORMAL = FraseTheme(
        id = "formal",
        title = "Формальное общение",
        cefr = "B2",
        phrases = listOf(
            flp("Уважаемый сеньор Гарсиа:", "Estimado señor García:",
                flt("Querido", "Деловое письмо — Estimado. Querido — личное")),
            flp("С уважением, Мария Лопес.", "Atentamente, María López.",
                flt("Besos,", "Besos — только близким! Деловой финал — Atentamente")),
            flp("Прилагаю своё резюме.", "Adjunto mi currículum.",
                flt("mío", "Перед существительным — mi, не mío")),
            flp("Пишу Вам, чтобы запросить информацию.", "Le escribo para solicitar información.",
                flt("Te", "Вежливое «Вам» (usted) = LE"),
                flt("por", "Цель = PARA solicitar")),
            flp("Заранее спасибо за Ваше внимание.", "Gracias de antemano por su atención.",
                flt("para", "Благодарить ЗА = POR"),
                flt("tu", "Usted → su atención")),
            flp("Не могли бы Вы прислать мне счёт?", "¿Podría enviarme la factura, por favor?",
                flt("Podrías", "Usted — podría"),
                flt("el", "Factura — женский род: la factura")),
            flp("Буду заранее благодарен за Ваш ответ.", "Le agradezco de antemano su respuesta.",
                flt("por", "Agradecer su respuesta — БЕЗ por"),
                flt("Te", "Usted → le agradezco")),
            flp("Извините за причинённые неудобства.", "Disculpe las molestias causadas.",
                flt("Disculpa", "Usted → disculpe"),
                flt("causados.", "Molestias — женский род: causadAs")),
            flp("Пожалуйста, подтвердите получение этого письма.", "Por favor, confirme la recepción de este correo.",
                flt("confirma", "Usted → императив confirme"),
                flt("esta", "Correo — мужской род: este")),
            flp("Мы свяжемся с Вами в ближайшее время.", "Nos pondremos en contacto con usted lo antes posible.",
                flt("contigo", "Формально — con usted"),
                flt("ponemos", "Будущее: nos pondremos")),
            flp("Сообщаю Вам, что собрание переносится на понедельник.", "Le comunico que la reunión se aplaza al lunes.",
                flt("Te", "Usted → le comunico"),
                flt("en", "На понедельник = al lunes")),
            flp("Прошу Вас решить эту проблему как можно скорее.", "Le ruego que solucione este problema cuanto antes.",
                flt("solucionar", "Le ruego QUE + subjuntivo: solucione"),
                flt("soluciona", "Subjuntivo: solucione"),
                flt("esta", "Problema — мужской род: este")),
        )
    )

    private val IDIOMAS = FraseTheme(
        id = "idiomas",
        title = "Идиомы и разговорная речь",
        cefr = "B2",
        phrases = listOf(
            flp("Это проще простого.", "Es pan comido.",
                flt("comida.", "Идиома: pan comido (m.)")),
            flp("Это не моё дело.", "No es asunto mío.",
                flt("mía.", "Asunto — мужской род: mío"),
                flt("está", "Характеристика — SER")),
            flp("Я в отличной форме.", "Estoy en plena forma.",
                flt("Soy", "Состояние — ESTAR"),
                flt("pleno", "Forma — женский род: plenA")),
            flp("Мне до лампочки.", "Me importa un pimiento.",
                flt("importan", "Un pimiento — ед.ч.: importa"),
                flt("una", "Pimiento — мужской род: un")),
            flp("Дождь льёт как из ведра.", "Está lloviendo a cántaros.",
                flt("Es", "Процесс сейчас — ESTAR + герундий"),
                flt("llover", "Estar + герундий: lloviendo")),
            flp("Мне это влетело в копеечку.", "Me costó un ojo de la cara.",
                flt("costaba", "Разовая покупка — Indefinido: costó"),
                flt("el", "Идиома: UN ojo de la cara")),
            flp("Он ходит вокруг да около.", "Se anda por las ramas.",
                flt("en", "Идиома: andarse POR las ramas")),
            flp("Держу за тебя кулачки!", "¡Cruzo los dedos por ti!",
                flt("para", "«За тебя» здесь = POR ti"),
                flt("las", "Dedos — мужской род: los dedos")),
            flp("Он встал не с той ноги.", "Se ha levantado con el pie izquierdo.",
                flt("la", "Pie — мужской род: el pie"),
                flt("levantada", "Причастие с haber не согласуется: levantado")),
            flp("Мы сразу поладили.", "Nos caímos bien desde el principio.",
                flt("gustamos", "«Поладить» = caerse bien"),
                flt("caemos", "В прошлом: caímos")),
            flp("Не выноси мне мозг!", "¡No me comas la cabeza!",
                flt("comes", "Запрет = no + subjuntivo: no comas"),
                flt("el", "Cabeza — женский род: la cabeza")),
            flp("Он за словом в карман не лезет.", "No tiene pelos en la lengua.",
                flt("el", "Lengua — женский род: la lengua"),
                flt("pelo", "Идиома во множественном: pelos")),
        )
    )

    private val CULTURA = FraseTheme(
        id = "cultura",
        title = "Культура и Испания",
        cefr = "B2",
        phrases = listOf(
            flp("Фламенко родилось в Андалусии.", "El flamenco nació en Andalucía.",
                flt("La", "Flamenco — мужской род: el flamenco"),
                flt("nacía", "Факт-событие — Indefinido: nació")),
            flp("В Испании обедают в два или в три.", "En España se come a las dos o a las tres.",
                flt("comen", "Безличное: se come"),
                flt("los", "Время — женский артикль: a LAS dos")),
            flp("Чем южнее, тем позже ужин.", "Cuanto más al sur, más tarde se cena.",
                flt("Que", "«Чем... тем» = CUANTO más..., más"),
                flt("cenan.", "Безличное: se cena")),
            flp("В Испании говорят не только по-испански.", "En España no solo se habla español.",
                flt("hablan", "Безличное: se habla")),
            flp("Испанцы ужинают очень поздно, около десяти.", "Los españoles cenan muy tarde, sobre las diez.",
                flt("cena", "Los españoles — множественное: cenaN"),
                flt("en", "«Около десяти» = sobre las diez")),
            flp("Многие магазины закрываются в полдень.", "Muchas tiendas cierran a mediodía.",
                flt("Muchos", "Tiendas — женский род: muchAs"),
                flt("en", "«В полдень» = a mediodía")),
            flp("Кто рано встаёт, тому Бог подаёт.", "A quien madruga, Dios le ayuda.",
                flt("Al", "Пословица: A quien madruga, без артикля"),
                flt("lo", "Ayudar кому — LE ayuda")),
            flp("Новый год испанцы встречают двенадцатью виноградинами.", "Los españoles reciben el año nuevo con doce uvas.",
                flt("doces", "Doce не изменяется: doce uvas"),
                flt("nueva", "Año — мужской род: nuevo")),
            flp("Испанская тортилья — из картофеля, а не из кукурузы.", "La tortilla española es de patatas, no de maíz.",
                flt("El", "Tortilla — женский род: la tortilla"),
                flt("está", "Состав/сущность — SER: es de patatas")),
            flp("В Испании при встрече принято целовать дважды.", "En España se dan dos besos al saludarse.",
                flt("da", "Dos besos — множественное: se daN"),
                flt("saludar.", "«При встрече» = al saludarSE (взаимное se)")),
            flp("Сиеста — это не только сон, это отдых.", "La siesta no es solo dormir, es descanso.",
                flt("está", "Определение понятия — SER")),
            flp("Выучить испанский — лучшее решение в моей жизни.", "Aprender español es la mejor decisión de mi vida.",
                flt("el", "Decisión — женский род: la mejor"),
                flt("en", "«В моей жизни» здесь = DE mi vida")),
        )
    )

    val themes: List<FraseTheme> =
        listOf(SUBJUNTIVO2, PASIVA, FORMAL, IDIOMAS, CULTURA)
}
