package com.spanishapp.ui.games

/**
 * Frase Loca — банк B1 (уровни 51–75, темы 11–15).
 * Ядро: Presente de Subjuntivo, Condicional, косвенная речь,
 * устойчивые конструкции (tener razón, estar de acuerdo, doler).
 */
internal object FraseLocaBankB1 {

    private val DESEOS = FraseTheme(
        id = "deseos",
        title = "Желания и советы · Subjuntivo",
        cefr = "B1",
        phrases = listOf(
            flp("Удачи тебе!", "¡Que tengas suerte!",
                flt("tienes", "Пожелание = que + subjuntivo: tengas"),
                flt("tener", "После que — личная форма, не инфинитив")),
            flp("Возможно, завтра пойдёт дождь.", "Quizás mañana llueva.",
                flt("lloverá", "Quizás + сомнение — subjuntivo: llueva"),
                flt("llueve.", "Не indicativo: llueva")),
            flp("Надеюсь, что всё пройдёт хорошо.", "Espero que todo salga bien.",
                flt("saldrá", "Espero que — subjuntivo: salga"),
                flt("sale", "Не indicativo: salga")),
            flp("Мне нужно, чтобы ты мне помог.", "Necesito que me ayudes.",
                flt("ayudas.", "Necesito que — subjuntivo: ayudes"),
                flt("ayudar.", "Разные подлежащие — que + subjuntivo, не инфинитив")),
            flp("Я хочу, чтобы ты пришёл на мою вечеринку.", "Quiero que vengas a mi fiesta.",
                flt("vienes", "Quiero que — subjuntivo: vengas"),
                flt("venir", "Разные подлежащие — que + subjuntivo")),
            flp("Не думаю, что это хорошая идея.", "No creo que sea una buena idea.",
                flt("es", "NO creo que — subjuntivo: sea"),
                flt("está", "Характеристика идеи — SER")),
            flp("Советую тебе больше отдыхать.", "Te aconsejo que descanses más.",
                flt("descansas", "Aconsejar que — subjuntivo: descanses"),
                flt("descansarás", "Не будущее: subjuntivo descanses")),
            flp("Когда приедешь, позвони мне.", "Cuando llegues, llámame.",
                flt("llegas,", "Cuando о будущем — subjuntivo: llegues"),
                flt("llegarás,", "После cuando нет будущего времени")),
            flp("Врач рекомендует, чтобы я меньше работал.", "El médico recomienda que trabaje menos.",
                flt("trabajo", "Recomienda que — subjuntivo: trabaje"),
                flt("trabajaré", "Не будущее: subjuntivo trabaje")),
            flp("Важно, чтобы вы говорили по-испански каждый день.", "Es importante que habléis español todos los días.",
                flt("habláis", "Es importante que — subjuntivo: habléis"),
                flt("hablan", "Vosotros: habléis (Испания)")),
            flp("Ищу квартиру, в которой много света.", "Busco un piso que tenga mucha luz.",
                flt("tiene", "Неопределённая квартира (ищу любую) — subjuntivo: tenga"),
                flt("mucho", "Luz — женский род: muchA luz")),
            flp("Я хочу, чтобы мои дети были счастливы.", "Quiero que mis hijos sean felices.",
                flt("son", "Quiero que — subjuntivo: sean"),
                flt("felizes.", "Орфография: z → c во мн.ч. — felices")),
        )
    )

    private val HIPOTESIS = FraseTheme(
        id = "hipotesis",
        title = "Гипотезы и вежливость · Condicional",
        cefr = "B1",
        phrases = listOf(
            flp("Ты не мог бы мне помочь?", "¿Podrías ayudarme?",
                flt("Poderías", "Poder — неправильная основа: podría"),
                flt("me", "Местоимение приклеивается к инфинитиву: ayudarme")),
            flp("Мне бы хотелось жить у моря.", "Me gustaría vivir junto al mar.",
                flt("gusta", "«Хотелось бы» — condicional: gustaría"),
                flt("viviría", "После gustaría — инфинитив: vivir")),
            flp("На твоём месте я бы поговорил с ней.", "Yo que tú, hablaría con ella.",
                flt("hablaré", "«Бы» = condicional: hablaría"),
                flt("hablaba", "Не imperfecto: hablaría")),
            flp("Было бы лучше выйти пораньше.", "Sería mejor salir más temprano.",
                flt("Estaría", "Оценка «было бы лучше» — SER: sería"),
                flt("saldría", "После sería mejor — инфинитив: salir")),
            flp("Я бы предпочёл остаться дома.", "Preferiría quedarme en casa.",
                flt("Prefería", "«Бы» = condicional preferiría, не imperfecto"),
                flt("quedar", "Остаться = quedarSE: quedarme")),
            flp("Что бы ты сделал с миллионом евро?", "¿Qué harías con un millón de euros?",
                flt("hacerías", "Hacer — неправильная основа: haría, harías"),
                flt("harás", "«Бы» = condicional: harías")),
            flp("Я бы съел ещё кусочек торта.", "Me comería otro trozo de tarta.",
                flt("comeré", "«Бы» = condicional: comería"),
                flt("otra", "Trozo — мужской род: otro trozo")),
            flp("Могли бы Вы говорить помедленнее?", "¿Podría usted hablar más despacio?",
                flt("Podrías", "Usted — третье лицо: podría"),
                flt("rápido?", "Помедленнее = despacio. Rápido — «быстро»")),
            flp("Наверное, было часов десять.", "Serían las diez, más o menos.",
                flt("Eran", "Догадка о прошлом — condicional: serían"),
                flt("Serán", "О прошлом — serían, не будущее")),
            flp("Без тебя я бы не смог это сделать.", "Sin ti no podría hacerlo.",
                flt("podería", "Poder — неправильная основа: podría"),
                flt("lo", "Lo приклеивается к инфинитиву: hacerlo")),
            flp("Если бы у меня было время, я бы больше путешествовал.", "Si tuviera tiempo, viajaría más.",
                flt("tendría", "После SI — subjuntivo imperfecto: tuviera"),
                flt("viajara", "В главной части — condicional: viajaría")),
            flp("Если бы я знал, я бы тебе сказал.", "Si lo supiera, te lo diría.",
                flt("sabría", "После SI — subjuntivo: supiera"),
                flt("diré.", "В главной части — condicional: diría")),
        )
    )

    private val RECADOS = FraseTheme(
        id = "recados",
        title = "Чужие слова · косвенная речь",
        cefr = "B1",
        phrases = listOf(
            flp("Хуан говорит, что не может прийти.", "Juan dice que no puede venir.",
                flt("pueda", "Dice que (утверждение) — indicativo: puede")),
            flp("Мария говорит, что придёт завтра.", "María dice que vendrá mañana.",
                flt("vendría", "Dice (настоящее) — сдвига нет: vendrá")),
            flp("Скажи ему, чтобы он подождал меня.", "Dile que me espere.",
                flt("espera.", "Просьба в que — subjuntivo: espere"),
                flt("esperará.", "Не будущее: subjuntivo espere")),
            flp("Он сказал, что был очень занят.", "Dijo que estaba muy ocupado.",
                flt("está", "Dijo — сдвиг времени: estaba"),
                flt("era", "Занятость — состояние: ESTAR")),
            flp("Она спросила меня, где я живу.", "Me preguntó dónde vivía.",
                flt("vivo.", "Preguntó — сдвиг времени: vivía"),
                flt("viva.", "Вопрос — indicativo со сдвигом, не subjuntivo")),
            flp("Он спросил меня, устал ли я.", "Me preguntó si estaba cansado.",
                flt("estoy", "Сдвиг времени: estaba"),
                flt("era", "Усталость — ESTAR")),
            flp("Мама спросила, поел ли я.", "Mamá me preguntó si había comido.",
                flt("comí.", "До её вопроса — предпрошедшее: había comido"),
                flt("ha", "Сдвиг: he comido → había comido")),
            flp("Я не знал, что ты уже приехал.", "No sabía que ya habías llegado.",
                flt("has", "Сдвиг: has llegado → habías llegado"),
                flt("llegabas.", "Результат к моменту — había + причастие")),
            flp("Они сказали, что раньше жили здесь.", "Dijeron que antes vivían aquí.",
                flt("viven", "Dijeron — сдвиг времени: vivían"),
                flt("vivieron", "Привычное прошлое — Imperfecto: vivían")),
            flp("Она сказала, что позвонит мне на следующий день.", "Dijo que me llamaría al día siguiente.",
                flt("llamará", "Сдвиг: будущее → condicional llamaría"),
                flt("mañana.", "В косвенной речи mañana → al día siguiente")),
            flp("Врач посоветовал, чтобы я больше гулял.", "El médico me aconsejó que paseara más.",
                flt("paseo", "Aconsejó que — subjuntivo прошлого: paseara"),
                flt("pasee", "Сдвиг в прошлое: pasee → paseara")),
            flp("Учитель сказал нам, чтобы мы делали задания каждый день.", "El profesor nos dijo que hiciéramos los deberes todos los días.",
                flt("hacíamos", "Просьба в косвенной речи — subjuntivo: hiciéramos"),
                flt("hagamos", "Dijo — сдвиг в прошлое: hiciéramos")),
        )
    )

    private val SALUD = FraseTheme(
        id = "salud",
        title = "Здоровье и самочувствие",
        cefr = "B1",
        phrases = listOf(
            flp("У меня болит голова.", "Me duele la cabeza.",
                flt("Mi", "Части тела — с артиклем: LA cabeza"),
                flt("duelen", "La cabeza — единственное число: duele")),
            flp("У меня температура и кашель.", "Tengo fiebre y tos.",
                flt("la", "Tengo fiebre — без артикля")),
            flp("Береги себя!", "¡Cuídate mucho!",
                flt("Te", "Императив: местоимение приклеивается — cuídaTE")),
            flp("Тебе надо отдохнуть.", "Tienes que descansar.",
                flt("de", "Tener que — без de. Debe DE = вероятность"),
                flt("descansas.", "После tienes que — инфинитив")),
            flp("Прими таблетку каждые восемь часов.", "Toma una pastilla cada ocho horas.",
                flt("Tomas", "Императив «прими» = toma"),
                flt("un", "Pastilla — женский род: una")),
            flp("Врач выписал мне антибиотики.", "El médico me recetó antibióticos.",
                flt("recetaba", "Разовое действие — Indefinido: recetó")),
            flp("Надеюсь, ты скоро поправишься.", "Espero que te mejores pronto.",
                flt("mejoras", "Espero que — subjuntivo: mejores"),
                flt("mejorarás", "Не будущее: subjuntivo mejores")),
            flp("У неё болят ноги после тренировки.", "Le duelen las piernas después del entrenamiento.",
                flt("duele", "Las piernas — множественное: duelen"),
                flt("sus", "Части тела — с артиклем las, не sus")),
            flp("Ты выглядишь уставшим. Ты хорошо спал?", "Pareces cansado. ¿Has dormido bien?",
                flt("dormiste", "Недавний сон (сегодняшняя ночь) — Perfecto"),
                flt("cansada.", "Речь о мужчине: cansadO")),
            flp("Врач говорит, чтобы я не курил.", "El médico me dice que no fume.",
                flt("fumo.", "Указание врача — subjuntivo: fume"),
                flt("fumar.", "После que — личная форма")),
            flp("Я записался к зубному на четверг.", "He pedido cita con el dentista para el jueves.",
                flt("en", "На четверг = para el jueves"),
                flt("pedida", "Причастие с haber не согласуется: pedido")),
            flp("Если тебе не станет лучше, сходи к врачу.", "Si no te encuentras mejor, ve al médico.",
                flt("va", "Императив «иди» (tú) = ve"),
                flt("encontrarás", "После si — настоящее: te encuentras")),
        )
    )

    private val OPINIONES = FraseTheme(
        id = "opiniones",
        title = "Мнения и споры",
        cefr = "B1",
        phrases = listOf(
            flp("Я считаю, что ты прав.", "Creo que tienes razón.",
                flt("eres", "Быть правым = TENER razón")),
            flp("Это зависит от погоды.", "Depende del tiempo.",
                flt("de", "de + el = DEL: del tiempo")),
            flp("Я с тобой не согласен.", "No estoy de acuerdo contigo.",
                flt("soy", "Согласие — ESTAR de acuerdo"),
                flt("ti.", "«С тобой» = contigo, одним словом")),
            flp("Честно говоря, мне всё равно.", "La verdad, me da igual.",
                flt("es", "Устойчиво: me DA igual")),
            flp("Мне кажется, что будет дождь.", "Me parece que va a llover.",
                flt("llueva.", "Me parece que — indicativo: va a llover")),
            flp("Не думаю, что он придёт.", "No creo que venga.",
                flt("viene.", "No creo que — subjuntivo: venga"),
                flt("vendrá.", "Не будущее: subjuntivo venga")),
            flp("По-моему, этот фильм скучный.", "Para mí, esta película es aburrida.",
                flt("está", "Характеристика фильма — SER. Estar aburrido = скучать"),
                flt("aburrido.", "Película — женский род: aburridA")),
            flp("Ты уверен, что это хорошая идея?", "¿Estás seguro de que es una buena idea?",
                flt("Eres", "Уверенность — ESTAR seguro"),
                flt("sea", "Estás seguro de que — indicativo: es")),
            flp("Нет смысла спорить.", "No tiene sentido discutir.",
                flt("hay", "Устойчиво: no TIENE sentido")),
            flp("Чем больше читаю, тем больше понимаю.", "Cuanto más leo, más entiendo.",
                flt("Que", "«Чем больше» = CUANTO más"),
                flt("entendo.", "E → IE: entiendo")),
            flp("Хотя это трудно, оно того стоит.", "Aunque es difícil, vale la pena.",
                flt("está", "Характеристика — SER: es difícil"),
                flt("el", "Pena — женский род: la pena")),
            flp("С одной стороны, это дорого; с другой — качественно.", "Por un lado es caro; por otro, es de calidad.",
                flt("Para", "«С одной стороны» = POR un lado"),
                flt("cara;", "Речь про «это» (м.р.): caro")),
        )
    )

    val themes: List<FraseTheme> = listOf(DESEOS, HIPOTESIS, RECADOS, SALUD, OPINIONES)
}
