package com.spanishapp.ui.games

/**
 * Словарь: испанское слово (без артикля, lowercase) → эмодзи.
 * Используется в игре Artículos для наглядности.
 */
object WordEmoji {

    private val map: Map<String, String> = mapOf(
        // ── Животные ────────────────────────────────────────
        "gato"        to "🐱",
        "perro"       to "🐶",
        "pájaro"      to "🐦",
        "pez"         to "🐟",
        "caballo"     to "🐴",
        "vaca"        to "🐮",
        "cerdo"       to "🐷",
        "pollo"       to "🐔",
        "conejo"      to "🐰",
        "ratón"       to "🐭",
        "oso"         to "🐻",
        "lobo"        to "🐺",
        "tortuga"     to "🐢",
        "serpiente"   to "🐍",
        "mariposa"    to "🦋",
        "abeja"       to "🐝",
        "araña"       to "🕷️",
        "hormiga"     to "🐜",
        "León"        to "🦁",
        "leon"        to "🦁",
        "tigre"       to "🐯",
        "elefante"    to "🐘",
        "mono"        to "🐒",
        "jirafa"      to "🦒",
        "cebra"       to "🦓",
        "cocodrilo"   to "🐊",
        "pingüino"    to "🐧",
        "ballena"     to "🐋",
        "delfín"      to "🐬",
        "pulpo"       to "🐙",

        // ── Еда и напитки ────────────────────────────────────
        "manzana"     to "🍎",
        "naranja"     to "🍊",
        "plátano"     to "🍌",
        "uva"         to "🍇",
        "fresa"       to "🍓",
        "sandía"      to "🍉",
        "limón"       to "🍋",
        "pera"        to "🍐",
        "melocotón"   to "🍑",
        "cereza"      to "🍒",
        "piña"        to "🍍",
        "mango"       to "🥭",
        "tomate"      to "🍅",
        "zanahoria"   to "🥕",
        "patata"      to "🥔",
        "maíz"        to "🌽",
        "brócoli"     to "🥦",
        "lechuga"     to "🥬",
        "cebolla"     to "🧅",
        "ajo"         to "🧄",
        "pimiento"    to "🫑",
        "pepino"      to "🥒",
        "calabaza"    to "🎃",
        "pan"         to "🍞",
        "pizza"       to "🍕",
        "hamburguesa" to "🍔",
        "taco"        to "🌮",
        "sopa"        to "🍲",
        "arroz"       to "🍚",
        "pasta"       to "🍝",
        "ensalada"    to "🥗",
        "huevo"       to "🥚",
        "queso"       to "🧀",
        "leche"       to "🥛",
        "café"        to "☕",
        "té"          to "🍵",
        "agua"        to "💧",
        "vino"        to "🍷",
        "cerveza"     to "🍺",
        "jugo"        to "🧃",
        "zumo"        to "🧃",
        "helado"      to "🍦",
        "pastel"      to "🎂",
        "galleta"     to "🍪",
        "chocolate"   to "🍫",
        "caramelo"    to "🍬",
        "miel"        to "🍯",
        "mantequilla" to "🧈",

        // ── Дом ──────────────────────────────────────────────
        "casa"        to "🏠",
        "puerta"      to "🚪",
        "ventana"     to "🪟",
        "mesa"        to "🪑",
        "silla"       to "🪑",
        "sofá"        to "🛋️",
        "cama"        to "🛏️",
        "lámpara"     to "💡",
        "espejo"      to "🪞",
        "televisión"  to "📺",
        "television"  to "📺",
        "nevera"      to "🧊",
        "microondas"  to "📡",
        "cocina"      to "🍳",
        "horno"       to "🔥",
        "baño"        to "🛁",
        "ducha"       to "🚿",
        "inodoro"     to "🚽",
        "escalera"    to "🪜",
        "jardín"      to "🌳",
        "garaje"      to "🚗",
        "llave"       to "🔑",

        // ── Одежда ───────────────────────────────────────────
        "camisa"      to "👔",
        "camiseta"    to "👕",
        "pantalón"    to "👖",
        "pantalones"  to "👖",
        "falda"       to "👗",
        "vestido"     to "👗",
        "abrigo"      to "🧥",
        "chaqueta"    to "🥼",
        "jersey"      to "🧶",
        "zapato"      to "👟",
        "zapatos"     to "👟",
        "bota"        to "🥾",
        "botas"       to "🥾",
        "sandalia"    to "👡",
        "calcetín"    to "🧦",
        "sombrero"    to "👒",
        "gorra"       to "🧢",
        "gafas"       to "👓",
        "bolso"       to "👜",
        "mochila"     to "🎒",
        "cinturón"    to "🩲",
        "guante"      to "🧤",
        "bufanda"     to "🧣",
        "paraguas"    to "☂️",

        // ── Транспорт ────────────────────────────────────────
        "coche"       to "🚗",
        "carro"       to "🚗",
        "autobús"     to "🚌",
        "autobus"     to "🚌",
        "metro"       to "🚇",
        "tren"        to "🚆",
        "avión"       to "✈️",
        "avion"       to "✈️",
        "barco"       to "🚢",
        "bicicleta"   to "🚲",
        "moto"        to "🏍️",
        "motocicleta" to "🏍️",
        "taxi"        to "🚕",
        "camión"      to "🚛",
        "helicóptero" to "🚁",
        "cohete"      to "🚀",
        "barca"       to "⛵",

        // ── Природа ──────────────────────────────────────────
        "sol"         to "☀️",
        "luna"        to "🌙",
        "estrella"    to "⭐",
        "nube"        to "☁️",
        "lluvia"      to "🌧️",
        "nieve"       to "❄️",
        "viento"      to "💨",
        "flor"        to "🌸",
        "árbol"       to "🌳",
        "arbol"       to "🌳",
        "hoja"        to "🍃",
        "hierba"      to "🌿",
        "montaña"     to "⛰️",
        "mar"         to "🌊",
        "río"         to "🏞️",
        "lago"        to "💧",
        "playa"       to "🏖️",
        "volcán"      to "🌋",
        "bosque"      to "🌲",
        "desierto"    to "🏜️",
        "tierra"      to "🌍",
        "fuego"       to "🔥",
        "piedra"      to "🪨",
        "arena"       to "🏝️",

        // ── Тело ─────────────────────────────────────────────
        "ojo"         to "👁️",
        "nariz"       to "👃",
        "boca"        to "👄",
        "oreja"       to "👂",
        "mano"        to "✋",
        "pie"         to "🦶",
        "cabeza"      to "👤",
        "corazón"     to "❤️",
        "brazo"       to "💪",
        "pierna"      to "🦵",
        "dedo"        to "☝️",
        "diente"      to "🦷",
        "cerebro"     to "🧠",
        "hueso"       to "🦴",

        // ── Учёба и работа ───────────────────────────────────
        "libro"       to "📚",
        "cuaderno"    to "📓",
        "lápiz"       to "✏️",
        "lapiz"       to "✏️",
        "bolígrafo"   to "🖊️",
        "boligrafo"   to "🖊️",
        "mochila"     to "🎒",
        "escuela"     to "🏫",
        "colegio"     to "🏫",
        "universidad" to "🎓",
        "clase"       to "🏫",
        "profesor"    to "👨‍🏫",
        "profesora"   to "👩‍🏫",
        "alumno"      to "🧑‍🎓",
        "alumna"      to "🧑‍🎓",
        "examen"      to "📝",
        "diccionario" to "📖",
        "mapa"        to "🗺️",
        "pizarra"     to "🖊️",
        "regla"       to "📏",
        "tijeras"     to "✂️",
        "papel"       to "📄",
        "carpeta"     to "📁",

        // ── Технологии ───────────────────────────────────────
        "teléfono"    to "📱",
        "telefono"    to "📱",
        "móvil"       to "📱",
        "movil"       to "📱",
        "ordenador"   to "💻",
        "computadora" to "💻",
        "teclado"     to "⌨️",
        "ratón"       to "🖱️",
        "pantalla"    to "🖥️",
        "cámara"      to "📷",
        "camara"      to "📷",
        "impresora"   to "🖨️",
        "auricular"   to "🎧",
        "altavoz"     to "🔊",
        "robot"       to "🤖",
        "cohete"      to "🚀",

        // ── Спорт и игры ─────────────────────────────────────
        "pelota"      to "⚽",
        "balón"       to "🏀",
        "balon"       to "🏀",
        "fútbol"      to "⚽",
        "futbol"      to "⚽",
        "tenis"       to "🎾",
        "natación"    to "🏊",
        "bicicleta"   to "🚲",
        "piscina"     to "🏊",
        "estadio"     to "🏟️",
        "juego"       to "🎮",
        "ajedrez"     to "♟️",
        "carta"       to "🃏",
        "cartas"      to "🃏",
        "dado"        to "🎲",
        "trofeo"      to "🏆",
        "medalla"     to "🏅",

        // ── Семья и люди ─────────────────────────────────────
        "madre"       to "👩",
        "padre"       to "👨",
        "mamá"        to "👩",
        "mama"        to "👩",
        "papá"        to "👨",
        "papa"        to "👨",
        "hijo"        to "👦",
        "hija"        to "👧",
        "hermano"     to "👦",
        "hermana"     to "👧",
        "abuelo"      to "👴",
        "abuela"      to "👵",
        "bebé"        to "👶",
        "bebe"        to "👶",
        "niño"        to "👦",
        "niña"        to "👧",
        "hombre"      to "👨",
        "mujer"       to "👩",
        "amigo"       to "🤝",
        "amiga"       to "🤝",
        "familia"     to "👨‍👩‍👧‍👦",

        // ── Место и здания ───────────────────────────────────
        "ciudad"      to "🏙️",
        "pueblo"      to "🏘️",
        "calle"       to "🛣️",
        "supermercado" to "🛒",
        "tienda"      to "🏪",
        "restaurante" to "🍽️",
        "hospital"    to "🏥",
        "farmacia"    to "💊",
        "banco"       to "🏦",
        "hotel"       to "🏨",
        "aeropuerto"  to "✈️",
        "estación"    to "🚉",
        "museo"       to "🏛️",
        "iglesia"     to "⛪",
        "parque"      to "🌳",
        "biblioteca"  to "📚",
        "mercado"     to "🛒",
        "oficina"     to "🏢",
        "fábrica"     to "🏭",
        "teatro"      to "🎭",
        "cine"        to "🎬",
        "estadio"     to "🏟️",

        // ── Разное ───────────────────────────────────────────
        "dinero"      to "💰",
        "moneda"      to "🪙",
        "billete"     to "💵",
        "regalo"      to "🎁",
        "globo"       to "🎈",
        "fiesta"      to "🎉",
        "música"      to "🎵",
        "musica"      to "🎵",
        "canción"     to "🎶",
        "cancion"     to "🎶",
        "guitarra"    to "🎸",
        "piano"       to "🎹",
        "micrófono"   to "🎤",
        "microfono"   to "🎤",
        "pintura"     to "🎨",
        "foto"        to "📸",
        "carta"       to "✉️",
        "sobre"       to "✉️",
        "paquete"     to "📦",
        "basura"      to "🗑️",
        "reloj"       to "⏰",
        "calendario"  to "📅",
        "bandera"     to "🚩",
        "luz"         to "💡",
        "fuente"      to "⛲",
        "semáforo"    to "🚦",
        "señal"       to "🚧",
        "herramienta" to "🔧",
        "martillo"    to "🔨",
        "llave inglesa" to "🔧",
        "tijeras"     to "✂️",
        "aguja"       to "🪡",
        "hilo"        to "🧵",
        "vela"        to "🕯️",
        "globo terráqueo" to "🌍",
        "corona"      to "👑",
        "anillo"      to "💍",
        "collar"      to "📿",
        "perfume"     to "🌺",
        "jabón"       to "🧼",
        "jabon"       to "🧼",
        "champú"      to "🚿",
        "champu"      to "🚿",
        "toalla"      to "🏊",
        "cepillo"     to "🪥",
        "peine"       to "💈"
    )

    /** Возвращает эмодзи для слова или null если нет в словаре. */
    fun get(word: String): String? = map[word.trim().lowercase()]
}
