import json

# НОВЫЕ ГЛАГОЛЫ (+100) — A2/B1/B2
new_verbs = [
  {'spanish':'desayunar','russian':'завтракать','example':'Desayuno a las ocho.','level':'A2','category':'cotidiano'},
  {'spanish':'almorzar','russian':'обедать','example':'Almorzamos juntos en el trabajo.','level':'A2','category':'cotidiano'},
  {'spanish':'cenar','russian':'ужинать','example':'Cenamos tarde los fines de semana.','level':'A2','category':'cotidiano'},
  {'spanish':'ducharse','russian':'принимать душ','example':'Me ducho cada mañana.','level':'A2','category':'cotidiano'},
  {'spanish':'vestirse','russian':'одеваться','example':'Los niños se visten solos.','level':'A2','category':'cotidiano'},
  {'spanish':'peinarse','russian':'причёсываться','example':'Se peina frente al espejo.','level':'A2','category':'cotidiano'},
  {'spanish':'afeitarse','russian':'бриться','example':'Mi padre se afeita cada dia.','level':'A2','category':'cotidiano'},
  {'spanish':'lavarse','russian':'умываться / мыться','example':'Lavate las manos antes de comer.','level':'A2','category':'cotidiano'},
  {'spanish':'acostarse','russian':'ложиться спать','example':'Me acuesto a las once.','level':'A2','category':'cotidiano'},
  {'spanish':'levantarse','russian':'вставать','example':'Me levanto temprano los lunes.','level':'A2','category':'cotidiano'},
  {'spanish':'despertarse','russian':'просыпаться','example':'Me despierto sin alarma.','level':'A2','category':'cotidiano'},
  {'spanish':'bañarse','russian':'купаться','example':'Los ninos se bañan por la noche.','level':'A2','category':'cotidiano'},
  {'spanish':'cepillarse','russian':'чистить зубы','example':'Cepillate los dientes tres veces al dia.','level':'A2','category':'cotidiano'},
  {'spanish':'maquillarse','russian':'краситься','example':'Tarda media hora en maquillarse.','level':'A2','category':'cotidiano'},
  {'spanish':'prepararse','russian':'готовиться','example':'Me preparo para el examen.','level':'A2','category':'cotidiano'},
  {'spanish':'quedarse','russian':'оставаться','example':'Me quedo en casa este fin de semana.','level':'A2','category':'acciones'},
  {'spanish':'sentarse','russian':'садиться','example':'Sientate aqui, por favor.','level':'A2','category':'acciones'},
  {'spanish':'ponerse','russian':'надевать / становиться','example':'Ponte el abrigo, hace frio.','level':'A2','category':'acciones'},
  {'spanish':'quitarse','russian':'снимать (одежду)','example':'Quitate los zapatos al entrar.','level':'A2','category':'acciones'},
  {'spanish':'olvidar','russian':'забывать','example':'Siempre olvido las llaves.','level':'A2','category':'pensamiento'},
  {'spanish':'recordar','russian':'помнить / вспоминать','example':'No recuerdo su nombre.','level':'A2','category':'pensamiento'},
  {'spanish':'cambiar','russian':'менять / меняться','example':'Cambia de opinion muy rapido.','level':'A2','category':'acciones'},
  {'spanish':'mejorar','russian':'улучшать / улучшаться','example':'Mi español mejora cada dia.','level':'A2','category':'acciones'},
  {'spanish':'empezar','russian':'начинать','example':'Empezamos a las nueve.','level':'A2','category':'acciones'},
  {'spanish':'terminar','russian':'заканчивать','example':'Cuando terminas el trabajo?','level':'A2','category':'acciones'},
  {'spanish':'continuar','russian':'продолжать','example':'Continua leyendo, por favor.','level':'A2','category':'acciones'},
  {'spanish':'dejar','russian':'оставлять / бросать','example':'Deje de fumar hace un año.','level':'A2','category':'acciones'},
  {'spanish':'seguir','russian':'продолжать / следовать','example':'Sigue recto hasta el semaforo.','level':'A2','category':'movimiento'},
  {'spanish':'parar','russian':'останавливаться','example':'Para el coche aqui.','level':'A2','category':'movimiento'},
  {'spanish':'girar','russian':'поворачивать','example':'Gira a la derecha en el cruce.','level':'A2','category':'movimiento'},
  {'spanish':'cruzar','russian':'пересекать / переходить','example':'Cruza la calle con cuidado.','level':'A2','category':'movimiento'},
  {'spanish':'subir','russian':'подниматься / садиться в транспорт','example':'Sube al autobus en esta parada.','level':'A2','category':'movimiento'},
  {'spanish':'bajar','russian':'спускаться / выходить из транспорта','example':'Baja en la proxima parada.','level':'A2','category':'movimiento'},
  {'spanish':'entrar','russian':'входить','example':'Entra y sientate.','level':'A2','category':'movimiento'},
  {'spanish':'buscar','russian':'искать','example':'Busco un apartamento en el centro.','level':'A2','category':'acciones'},
  {'spanish':'encontrar','russian':'находить','example':'Encontre mi cartera debajo del sofa.','level':'A2','category':'acciones'},
  {'spanish':'perder','russian':'терять / проигрывать','example':'Perdi el tren por diez minutos.','level':'A2','category':'acciones'},
  {'spanish':'ganar','russian':'выигрывать / зарабатывать','example':'Mi equipo gano el partido.','level':'A2','category':'deporte'},
  {'spanish':'jugar','russian':'играть','example':'Los ninos juegan en el parque.','level':'A2','category':'deporte'},
  {'spanish':'practicar','russian':'практиковать / тренироваться','example':'Practico español una hora al dia.','level':'A2','category':'educacion'},
  {'spanish':'preguntar','russian':'спрашивать','example':'Pregunta al profesor si no entiendes.','level':'A2','category':'comunicacion'},
  {'spanish':'responder','russian':'отвечать','example':'Responde a mis mensajes, por favor.','level':'A2','category':'comunicacion'},
  {'spanish':'explicar','russian':'объяснять','example':'El profesor explica la gramatica.','level':'A2','category':'comunicacion'},
  {'spanish':'contar','russian':'считать / рассказывать','example':'Cuentame que paso.','level':'A2','category':'comunicacion'},
  {'spanish':'invitar','russian':'приглашать','example':'Te invito a mi fiesta de cumpleaños.','level':'A2','category':'social'},
  {'spanish':'desarrollar','russian':'развивать','example':'Desarrollamos nuevas habilidades en el trabajo.','level':'B1','category':'trabajo'},
  {'spanish':'conseguir','russian':'добиваться / получать','example':'Consegvi el trabajo que queria.','level':'B1','category':'trabajo'},
  {'spanish':'lograr','russian':'достигать','example':'Logro aprobar el examen a la primera.','level':'B1','category':'educacion'},
  {'spanish':'superar','russian':'преодолевать','example':'Supero todos los obstaculos.','level':'B1','category':'emociones'},
  {'spanish':'adaptarse','russian':'адаптироваться','example':'Me adapte rapido al nuevo pais.','level':'B1','category':'acciones'},
  {'spanish':'aprovechar','russian':'использовать возможность','example':'Aprovecha cada oportunidad.','level':'B1','category':'acciones'},
  {'spanish':'rechazar','russian':'отвергать / отказывать','example':'Rechazo la oferta de trabajo.','level':'B1','category':'social'},
  {'spanish':'aceptar','russian':'принимать / соглашаться','example':'Acepta las criticas con madurez.','level':'B1','category':'social'},
  {'spanish':'confiar','russian':'доверять','example':'Confio en mis amigos completamente.','level':'B1','category':'emociones'},
  {'spanish':'dudar','russian':'сомневаться','example':'Dudo que tenga razon.','level':'B1','category':'pensamiento'},
  {'spanish':'imaginar','russian':'воображать','example':'Imagina un mundo sin guerras.','level':'B1','category':'pensamiento'},
  {'spanish':'sonar','russian':'мечтать / сниться','example':'Sueno con vivir en el extranjero.','level':'B1','category':'emociones'},
  {'spanish':'preocuparse','russian':'беспокоиться','example':'No te preocupes, todo saldra bien.','level':'B1','category':'emociones'},
  {'spanish':'relajarse','russian':'расслабляться','example':'Me relajo escuchando musica.','level':'B1','category':'emociones'},
  {'spanish':'divertirse','russian':'развлекаться / веселиться','example':'Nos divertimos mucho en la fiesta.','level':'B1','category':'emociones'},
  {'spanish':'emocionarse','russian':'волноваться / умиляться','example':'Me emociono al ver esa pelicula.','level':'B1','category':'emociones'},
  {'spanish':'enfadarse','russian':'злиться / обижаться','example':'Se enfada cuando llego tarde.','level':'B1','category':'emociones'},
  {'spanish':'alegrarse','russian':'радоваться','example':'Me alegro de verte.','level':'B1','category':'emociones'},
  {'spanish':'sorprender','russian':'удивлять','example':'Me sorprende tu valentia.','level':'B1','category':'emociones'},
  {'spanish':'discutir','russian':'спорить / обсуждать','example':'Discutimos sobre politica con frecuencia.','level':'B1','category':'comunicacion'},
  {'spanish':'negociar','russian':'договариваться','example':'Hay que negociar el precio.','level':'B1','category':'trabajo'},
  {'spanish':'planificar','russian':'планировать','example':'Planifica tu tiempo con cuidado.','level':'B1','category':'trabajo'},
  {'spanish':'organizar','russian':'организовывать','example':'Organiza los documentos por fecha.','level':'B1','category':'trabajo'},
  {'spanish':'resolver','russian':'решать проблему','example':'Resolvemos los problemas juntos.','level':'B1','category':'pensamiento'},
  {'spanish':'analizar','russian':'анализировать','example':'Analiza los datos antes de concluir.','level':'B1','category':'pensamiento'},
  {'spanish':'comparar','russian':'сравнивать','example':'Compara los dos precios.','level':'B1','category':'pensamiento'},
  {'spanish':'elegir','russian':'выбирать','example':'Elige el que mas te guste.','level':'B1','category':'acciones'},
  {'spanish':'preferir','russian':'предпочитать','example':'Prefiero el cafe al te.','level':'B1','category':'acciones'},
  {'spanish':'depender','russian':'зависеть','example':'Depende del tiempo que haga.','level':'B1','category':'general'},
  {'spanish':'funcionar','russian':'работать / функционировать','example':'El ordenador no funciona bien.','level':'B1','category':'tecnologia'},
  {'spanish':'instalar','russian':'устанавливать','example':'Instala la aplicacion en tu movil.','level':'B1','category':'tecnologia'},
  {'spanish':'descargar','russian':'скачивать','example':'Descarga el archivo desde la web.','level':'B1','category':'tecnologia'},
  {'spanish':'guardar','russian':'сохранять','example':'Guarda el documento antes de cerrar.','level':'B1','category':'tecnologia'},
  {'spanish':'compartir','russian':'делиться','example':'Comparte el enlace con tus amigos.','level':'B1','category':'tecnologia'},
  {'spanish':'publicar','russian':'публиковать','example':'Publica tus fotos en las redes sociales.','level':'B1','category':'tecnologia'},
  {'spanish':'demostrar','russian':'демонстрировать / доказывать','example':'Demostro su inocencia ante el juez.','level':'B2','category':'comunicacion'},
  {'spanish':'afirmar','russian':'утверждать','example':'Afirma que es inocente.','level':'B2','category':'comunicacion'},
  {'spanish':'negar','russian':'отрицать','example':'Nego haber estado alli.','level':'B2','category':'comunicacion'},
  {'spanish':'proponer','russian':'предлагать','example':'Propongo una solucion alternativa.','level':'B2','category':'comunicacion'},
  {'spanish':'exigir','russian':'требовать','example':'Exige un aumento de sueldo.','level':'B2','category':'trabajo'},
  {'spanish':'convencer','russian':'убеждать','example':'Me convencio de cambiar de trabajo.','level':'B2','category':'comunicacion'},
  {'spanish':'transformar','russian':'преобразовывать','example':'La tecnologia transforma la sociedad.','level':'B2','category':'general'},
  {'spanish':'contribuir','russian':'вносить вклад','example':'Contribuye activamente a la comunidad.','level':'B2','category':'social'},
  {'spanish':'garantizar','russian':'гарантировать','example':'No podemos garantizar los resultados.','level':'B2','category':'trabajo'},
  {'spanish':'establecer','russian':'устанавливать / учреждать','example':'Establecieron nuevas normas laborales.','level':'B2','category':'trabajo'},
  {'spanish':'implementar','russian':'внедрять','example':'Implementamos un nuevo sistema.','level':'B2','category':'trabajo'},
  {'spanish':'evaluar','russian':'оценивать','example':'El profesor evalua los examenes.','level':'B2','category':'educacion'},
  {'spanish':'reconocer','russian':'признавать / узнавать','example':'Reconocio su error ante todos.','level':'B2','category':'pensamiento'},
]

# НОВЫЕ СУЩЕСТВИТЕЛЬНЫЕ (+200)
new_nouns = [
  {'spanish':'la cabeza','russian':'голова','example':'Me duele la cabeza.','level':'A2','category':'cuerpo'},
  {'spanish':'el cuello','russian':'шея','example':'Lleva una bufanda en el cuello.','level':'A2','category':'cuerpo'},
  {'spanish':'el hombro','russian':'плечо','example':'Me duele el hombro derecho.','level':'A2','category':'cuerpo'},
  {'spanish':'el codo','russian':'локоть','example':'Se golpeo el codo con la mesa.','level':'A2','category':'cuerpo'},
  {'spanish':'la muneca','russian':'запястье','example':'Lleva un reloj en la muneca.','level':'A2','category':'cuerpo'},
  {'spanish':'el dedo','russian':'палец','example':'Se corto el dedo con el cuchillo.','level':'A2','category':'cuerpo'},
  {'spanish':'la rodilla','russian':'колено','example':'Me duele la rodilla al correr.','level':'A2','category':'cuerpo'},
  {'spanish':'el tobillo','russian':'лодыжка','example':'Se torcio el tobillo jugando al futbol.','level':'A2','category':'cuerpo'},
  {'spanish':'el pecho','russian':'грудь','example':'Le duele el pecho despues de correr.','level':'A2','category':'cuerpo'},
  {'spanish':'la espalda','russian':'спина','example':'Tengo dolor de espalda.','level':'A2','category':'cuerpo'},
  {'spanish':'el estomago','russian':'желудок','example':'Me duele el estomago despues de comer.','level':'A2','category':'cuerpo'},
  {'spanish':'la garganta','russian':'горло','example':'Tengo la garganta irritada.','level':'A2','category':'cuerpo'},
  {'spanish':'el armario','russian':'шкаф','example':'La ropa esta en el armario.','level':'A2','category':'casa'},
  {'spanish':'la estanteria','russian':'полка / стеллаж','example':'Los libros estan en la estanteria.','level':'A2','category':'casa'},
  {'spanish':'la lampara','russian':'лампа','example':'Enciende la lampara, por favor.','level':'A2','category':'casa'},
  {'spanish':'la almohada','russian':'подушка','example':'Necesito una almohada mas blanda.','level':'A2','category':'casa'},
  {'spanish':'la manta','russian':'одеяло','example':'Hace frio, ponme la manta.','level':'A2','category':'casa'},
  {'spanish':'el grifo','russian':'кран (водопроводный)','example':'El grifo del bano gotea.','level':'A2','category':'casa'},
  {'spanish':'la ducha','russian':'душ','example':'La ducha esta en el bano.','level':'A2','category':'casa'},
  {'spanish':'la banera','russian':'ванна','example':'Me relajo en la banera.','level':'A2','category':'casa'},
  {'spanish':'el espejo','russian':'зеркало','example':'Se mira en el espejo cada manana.','level':'A2','category':'casa'},
  {'spanish':'el microondas','russian':'микроволновка','example':'Calienta la comida en el microondas.','level':'A2','category':'casa'},
  {'spanish':'el frigorifico','russian':'холодильник','example':'Guarda la leche en el frigorifico.','level':'A2','category':'casa'},
  {'spanish':'el horno','russian':'духовка / печь','example':'Precalienta el horno a 180 grados.','level':'A2','category':'casa'},
  {'spanish':'la lavadora','russian':'стиральная машина','example':'Meto la ropa sucia en la lavadora.','level':'A2','category':'casa'},
  {'spanish':'el semaforo','russian':'светофор','example':'Para en el semaforo en rojo.','level':'A2','category':'ciudad'},
  {'spanish':'la acera','russian':'тротуар','example':'Camina por la acera, no por la calle.','level':'A2','category':'ciudad'},
  {'spanish':'el cruce','russian':'перекрёсток','example':'Gira a la izquierda en el cruce.','level':'A2','category':'ciudad'},
  {'spanish':'el puente','russian':'мост','example':'El puente cruza el rio.','level':'A2','category':'ciudad'},
  {'spanish':'la parada','russian':'остановка','example':'La parada del metro esta cerca.','level':'A2','category':'transporte'},
  {'spanish':'el anden','russian':'платформа (ж/д)','example':'El tren sale del anden tres.','level':'A2','category':'transporte'},
  {'spanish':'el billete','russian':'билет','example':'Compre el billete online.','level':'A2','category':'transporte'},
  {'spanish':'el equipaje','russian':'багаж','example':'Factura el equipaje antes de subir.','level':'A2','category':'transporte'},
  {'spanish':'la maleta','russian':'чемодан','example':'Mi maleta pesa veinte kilos.','level':'A2','category':'transporte'},
  {'spanish':'la mochila','russian':'рюкзак','example':'Lleva todos sus libros en la mochila.','level':'A2','category':'transporte'},
  {'spanish':'el desayuno','russian':'завтрак','example':'El desayuno se sirve de 7 a 10.','level':'A2','category':'comida'},
  {'spanish':'el almuerzo','russian':'обед','example':'El almuerzo es la comida principal.','level':'A2','category':'comida'},
  {'spanish':'la cena','russian':'ужин','example':'La cena fue deliciosa.','level':'A2','category':'comida'},
  {'spanish':'el postre','russian':'десерт','example':'De postre quiero flan.','level':'A2','category':'comida'},
  {'spanish':'la cuenta','russian':'счёт (в ресторане)','example':'Me trae la cuenta, por favor?','level':'A2','category':'comida'},
  {'spanish':'la propina','russian':'чаевые','example':'Dejamos una propina del 10%.','level':'A2','category':'comida'},
  {'spanish':'el menu','russian':'меню','example':'Tienen menu del dia?','level':'A2','category':'comida'},
  {'spanish':'la receta','russian':'рецепт','example':'Me das la receta de este plato?','level':'A2','category':'comida'},
  {'spanish':'el ingrediente','russian':'ингредиент','example':'Faltan ingredientes para la paella.','level':'A2','category':'comida'},
  {'spanish':'el sueldo','russian':'зарплата','example':'Su sueldo es de dos mil euros.','level':'B1','category':'trabajo'},
  {'spanish':'el contrato','russian':'контракт','example':'Firmo el contrato de trabajo.','level':'B1','category':'trabajo'},
  {'spanish':'la empresa','russian':'компания / предприятие','example':'Trabaja en una empresa internacional.','level':'B1','category':'trabajo'},
  {'spanish':'el jefe','russian':'начальник / шеф','example':'Mi jefe es muy exigente.','level':'B1','category':'trabajo'},
  {'spanish':'el empleado','russian':'сотрудник','example':'La empresa tiene cien empleados.','level':'B1','category':'trabajo'},
  {'spanish':'la reunion','russian':'встреча / совещание','example':'Tenemos una reunion a las diez.','level':'B1','category':'trabajo'},
  {'spanish':'el informe','russian':'доклад / отчёт','example':'Prepara el informe para el lunes.','level':'B1','category':'trabajo'},
  {'spanish':'el plazo','russian':'срок / дедлайн','example':'El plazo de entrega es manana.','level':'B1','category':'trabajo'},
  {'spanish':'el presupuesto','russian':'бюджет','example':'El presupuesto no es suficiente.','level':'B1','category':'trabajo'},
  {'spanish':'la entrevista','russian':'интервью / собеседование','example':'Tengo una entrevista de trabajo manana.','level':'B1','category':'trabajo'},
  {'spanish':'el curriculum','russian':'резюме','example':'Actualiza tu curriculum antes de aplicar.','level':'B1','category':'trabajo'},
  {'spanish':'el ascenso','russian':'повышение по службе','example':'Le dieron un ascenso este ano.','level':'B1','category':'trabajo'},
  {'spanish':'la sociedad','russian':'общество','example':'La sociedad cambia con la tecnologia.','level':'B1','category':'sociedad'},
  {'spanish':'el gobierno','russian':'правительство','example':'El gobierno aprobo la nueva ley.','level':'B1','category':'sociedad'},
  {'spanish':'la ley','russian':'закон','example':'Todos somos iguales ante la ley.','level':'B1','category':'sociedad'},
  {'spanish':'el derecho','russian':'право','example':'Tenemos derecho a la educacion.','level':'B1','category':'sociedad'},
  {'spanish':'la libertad','russian':'свобода','example':'La libertad de expresion es fundamental.','level':'B1','category':'sociedad'},
  {'spanish':'la igualdad','russian':'равенство','example':'Luchamos por la igualdad de genero.','level':'B1','category':'sociedad'},
  {'spanish':'el conflicto','russian':'конфликт','example':'Hay un conflicto entre los vecinos.','level':'B1','category':'sociedad'},
  {'spanish':'la solucion','russian':'решение / выход','example':'Buscamos una solucion al problema.','level':'B1','category':'general'},
  {'spanish':'el riesgo','russian':'риск','example':'Hay que calcular el riesgo antes de actuar.','level':'B1','category':'general'},
  {'spanish':'la oportunidad','russian':'возможность / шанс','example':'Es una gran oportunidad de negocio.','level':'B1','category':'trabajo'},
  {'spanish':'el exito','russian':'успех','example':'El exito requiere esfuerzo constante.','level':'B1','category':'emociones'},
  {'spanish':'el fracaso','russian':'неудача','example':'El fracaso nos ensena lecciones valiosas.','level':'B1','category':'emociones'},
  {'spanish':'el medio ambiente','russian':'окружающая среда','example':'Debemos proteger el medio ambiente.','level':'B1','category':'naturaleza'},
  {'spanish':'el cambio climatico','russian':'изменение климата','example':'El cambio climatico es una amenaza real.','level':'B1','category':'naturaleza'},
  {'spanish':'la contaminacion','russian':'загрязнение','example':'La contaminacion del aire es grave.','level':'B1','category':'naturaleza'},
  {'spanish':'el reciclaje','russian':'переработка / рециклинг','example':'El reciclaje reduce los residuos.','level':'B1','category':'naturaleza'},
  {'spanish':'la sequia','russian':'засуха','example':'La sequia afecta a muchas regiones.','level':'B1','category':'naturaleza'},
  {'spanish':'la inundacion','russian':'наводнение','example':'Las inundaciones destruyeron los campos.','level':'B1','category':'naturaleza'},
  {'spanish':'el terremoto','russian':'землетрясение','example':'Hubo un terremoto de magnitud 6.','level':'B1','category':'naturaleza'},
  {'spanish':'la inflacion','russian':'инфляция','example':'La inflacion reduce el poder adquisitivo.','level':'B2','category':'finanzas'},
  {'spanish':'la inversion','russian':'инвестиция','example':'Es una inversion a largo plazo.','level':'B2','category':'finanzas'},
  {'spanish':'la deuda','russian':'долг','example':'El pais tiene una deuda enorme.','level':'B2','category':'finanzas'},
  {'spanish':'el impuesto','russian':'налог','example':'El impuesto sobre la renta es progresivo.','level':'B2','category':'finanzas'},
  {'spanish':'el mercado','russian':'рынок','example':'El mercado laboral es muy competitivo.','level':'B2','category':'finanzas'},
  {'spanish':'la competencia','russian':'конкуренция','example':'La competencia entre empresas es feroz.','level':'B2','category':'trabajo'},
  {'spanish':'el beneficio','russian':'прибыль / польза','example':'La empresa obtuvo grandes beneficios.','level':'B2','category':'finanzas'},
  {'spanish':'la subvencion','russian':'субсидия','example':'El gobierno da subvenciones a las pymes.','level':'B2','category':'finanzas'},
]

# ПРИЛАГАТЕЛЬНЫЕ (+80)
new_adjectives = [
  {'spanish':'amable','russian':'вежливый / любезный','example':'El recepcionista es muy amable.','level':'A2','category':'personas'},
  {'spanish':'simpatico','russian':'приятный / симпатичный','example':'Tu amigo es muy simpatico.','level':'A2','category':'personas'},
  {'spanish':'antipatico','russian':'неприятный','example':'El nuevo vecino es un poco antipatico.','level':'A2','category':'personas'},
  {'spanish':'generoso','russian':'щедрый','example':'Es muy generoso con su tiempo.','level':'A2','category':'personas'},
  {'spanish':'egoista','russian':'эгоистичный','example':'No seas tan egoista, comparte.','level':'A2','category':'personas'},
  {'spanish':'honesto','russian':'честный','example':'Siempre ha sido una persona honesta.','level':'A2','category':'personas'},
  {'spanish':'mentiroso','russian':'лживый','example':'No confies en el, es mentiroso.','level':'A2','category':'personas'},
  {'spanish':'valiente','russian':'храбрый / смелый','example':'Es muy valiente enfrentarse a eso.','level':'A2','category':'personas'},
  {'spanish':'cobarde','russian':'трусливый','example':'No seas cobarde, habla con el.','level':'A2','category':'personas'},
  {'spanish':'paciente','russian':'терпеливый','example':'Los profesores tienen que ser pacientes.','level':'A2','category':'personas'},
  {'spanish':'impaciente','russian':'нетерпеливый','example':'Siempre esta impaciente en la cola.','level':'A2','category':'personas'},
  {'spanish':'curioso','russian':'любопытный','example':'Los ninos son muy curiosos.','level':'A2','category':'personas'},
  {'spanish':'emocionante','russian':'захватывающий / волнующий','example':'Fue una final muy emocionante.','level':'A2','category':'calidad'},
  {'spanish':'difícil','russian':'трудный / сложный','example':'El examen fue muy dificil.','level':'A2','category':'calidad'},
  {'spanish':'fácil','russian':'лёгкий / простой','example':'La tarea es facil para el.','level':'A2','category':'calidad'},
  {'spanish':'barato','russian':'дешёвый','example':'Este restaurante es muy barato.','level':'A2','category':'precio'},
  {'spanish':'caro','russian':'дорогой','example':'El alquiler en el centro es muy caro.','level':'A2','category':'precio'},
  {'spanish':'lleno','russian':'полный','example':'El autobus va lleno a esta hora.','level':'A2','category':'cantidad'},
  {'spanish':'vacio','russian':'пустой','example':'La sala de espera esta vacia.','level':'A2','category':'cantidad'},
  {'spanish':'limpio','russian':'чистый','example':'La habitacion esta muy limpia.','level':'A2','category':'calidad'},
  {'spanish':'sucio','russian':'грязный','example':'Los platos estan sucios.','level':'A2','category':'calidad'},
  {'spanish':'ordenado','russian':'аккуратный / прибранный','example':'Su escritorio esta siempre ordenado.','level':'A2','category':'calidad'},
  {'spanish':'desordenado','russian':'беспорядочный','example':'Su habitacion esta muy desordenada.','level':'A2','category':'calidad'},
  {'spanish':'roto','russian':'сломанный / разбитый','example':'La silla esta rota.','level':'A2','category':'estados'},
  {'spanish':'moderno','russian':'современный','example':'El diseno es muy moderno.','level':'A2','category':'calidad'},
  {'spanish':'antiguo','russian':'старинный / древний','example':'Es una ciudad con edificios antiguos.','level':'A2','category':'calidad'},
  {'spanish':'responsable','russian':'ответственный','example':'Es una persona muy responsable.','level':'B1','category':'personas'},
  {'spanish':'irresponsable','russian':'безответственный','example':'Su comportamiento es irresponsable.','level':'B1','category':'personas'},
  {'spanish':'ambicioso','russian':'амбициозный','example':'Es muy ambiciosa en su carrera.','level':'B1','category':'personas'},
  {'spanish':'creativo','russian':'творческий','example':'Necesitamos una solucion creativa.','level':'B1','category':'personas'},
  {'spanish':'flexible','russian':'гибкий','example':'Hay que ser flexible en el trabajo.','level':'B1','category':'personas'},
  {'spanish':'eficiente','russian':'эффективный','example':'Es un metodo muy eficiente.','level':'B1','category':'calidad'},
  {'spanish':'sostenible','russian':'устойчивый / экологичный','example':'Necesitamos un desarrollo sostenible.','level':'B1','category':'naturaleza'},
  {'spanish':'renovable','russian':'возобновляемый','example':'La energia solar es renovable.','level':'B1','category':'naturaleza'},
  {'spanish':'obligatorio','russian':'обязательный','example':'El uso del casco es obligatorio.','level':'B1','category':'general'},
  {'spanish':'disponible','russian':'доступный / свободный','example':'Esta disponible para una reunion?','level':'B1','category':'general'},
  {'spanish':'ocupado','russian':'занятой / занятый','example':'Estoy muy ocupado esta semana.','level':'B1','category':'estados'},
  {'spanish':'libre','russian':'свободный','example':'Estas libre el viernes por la tarde?','level':'B1','category':'estados'},
  {'spanish':'positivo','russian':'позитивный / положительный','example':'Tiene una actitud positiva.','level':'B1','category':'valor'},
  {'spanish':'negativo','russian':'негативный / отрицательный','example':'El resultado del test fue negativo.','level':'B1','category':'valor'},
  {'spanish':'relevante','russian':'актуальный / важный','example':'Es una cuestion muy relevante.','level':'B2','category':'valor'},
  {'spanish':'innovador','russian':'инновационный','example':'Es un enfoque muy innovador.','level':'B2','category':'calidad'},
  {'spanish':'competitivo','russian':'конкурентоспособный','example':'El mercado es muy competitivo.','level':'B2','category':'trabajo'},
  {'spanish':'rentable','russian':'рентабельный / выгодный','example':'El negocio es muy rentable.','level':'B2','category':'finanzas'},
  {'spanish':'imprescindible','russian':'незаменимый / обязательный','example':'Es imprescindible llevar el pasaporte.','level':'B2','category':'valor'},
  {'spanish':'exhaustivo','russian':'исчерпывающий / тщательный','example':'Hizo un analisis exhaustivo.','level':'B2','category':'calidad'},
]

# НАРЕЧИЯ (+70) — новый раздел
new_adverbs = [
  {'spanish':'ahora','russian':'сейчас','example':'Ahora estoy estudiando espanol.','level':'A1','category':'tiempo'},
  {'spanish':'hoy','russian':'сегодня','example':'Hoy tengo mucho trabajo.','level':'A1','category':'tiempo'},
  {'spanish':'manana','russian':'завтра','example':'Manana es mi cumpleanos.','level':'A1','category':'tiempo'},
  {'spanish':'ayer','russian':'вчера','example':'Ayer fui al medico.','level':'A1','category':'tiempo'},
  {'spanish':'siempre','russian':'всегда','example':'Siempre llego a tiempo.','level':'A1','category':'tiempo'},
  {'spanish':'nunca','russian':'никогда','example':'Nunca como carne.','level':'A1','category':'tiempo'},
  {'spanish':'a veces','russian':'иногда','example':'A veces voy al gimnasio.','level':'A1','category':'tiempo'},
  {'spanish':'pronto','russian':'скоро / рано','example':'Llegare pronto.','level':'A1','category':'tiempo'},
  {'spanish':'tarde','russian':'поздно','example':'Llegue tarde a la reunion.','level':'A1','category':'tiempo'},
  {'spanish':'temprano','russian':'рано','example':'Me levanto temprano cada dia.','level':'A1','category':'tiempo'},
  {'spanish':'ya','russian':'уже','example':'Ya he terminado el trabajo.','level':'A1','category':'tiempo'},
  {'spanish':'todavia','russian':'ещё / всё ещё','example':'Todavia no ha llegado.','level':'A2','category':'tiempo'},
  {'spanish':'luego','russian':'потом / затем','example':'Primero como, luego salgo.','level':'A1','category':'tiempo'},
  {'spanish':'despues','russian':'после / потом','example':'Despues de comer, salimos.','level':'A1','category':'tiempo'},
  {'spanish':'antes','russian':'раньше / до','example':'Antes vivia en Madrid.','level':'A1','category':'tiempo'},
  {'spanish':'finalmente','russian':'наконец','example':'Finalmente encontre trabajo.','level':'A2','category':'tiempo'},
  {'spanish':'enseguida','russian':'сразу / немедленно','example':'Vengo enseguida.','level':'A2','category':'tiempo'},
  {'spanish':'frecuentemente','russian':'часто','example':'Frecuentemente vamos al parque.','level':'A2','category':'tiempo'},
  {'spanish':'raramente','russian':'редко','example':'Raramente veo la television.','level':'A2','category':'tiempo'},
  {'spanish':'constantemente','russian':'постоянно','example':'Esta constantemente en el telefono.','level':'B1','category':'tiempo'},
  {'spanish':'recientemente','russian':'недавно','example':'Recientemente cambie de trabajo.','level':'B1','category':'tiempo'},
  {'spanish':'aqui','russian':'здесь','example':'Quedate aqui, vuelvo pronto.','level':'A1','category':'lugar'},
  {'spanish':'alli','russian':'там','example':'El bano esta alli a la derecha.','level':'A1','category':'lugar'},
  {'spanish':'arriba','russian':'вверху / наверху','example':'El apartamento esta arriba.','level':'A1','category':'lugar'},
  {'spanish':'abajo','russian':'внизу','example':'La cocina esta abajo.','level':'A1','category':'lugar'},
  {'spanish':'dentro','russian':'внутри','example':'El gato esta dentro de la caja.','level':'A1','category':'lugar'},
  {'spanish':'fuera','russian':'снаружи / вне','example':'Espera fuera, por favor.','level':'A1','category':'lugar'},
  {'spanish':'cerca','russian':'близко / рядом','example':'La farmacia esta muy cerca.','level':'A1','category':'lugar'},
  {'spanish':'lejos','russian':'далеко','example':'El aeropuerto esta lejos del centro.','level':'A1','category':'lugar'},
  {'spanish':'delante','russian':'впереди / перед','example':'El perro camina delante de nosotros.','level':'A2','category':'lugar'},
  {'spanish':'detras','russian':'сзади / за','example':'El jardin esta detras de la casa.','level':'A2','category':'lugar'},
  {'spanish':'bien','russian':'хорошо','example':'Hablas espanol muy bien.','level':'A1','category':'modo'},
  {'spanish':'mal','russian':'плохо','example':'Me siento mal hoy.','level':'A1','category':'modo'},
  {'spanish':'rapidamente','russian':'быстро','example':'Habla rapidamente.','level':'A2','category':'modo'},
  {'spanish':'lentamente','russian':'медленно','example':'Conduce lentamente en la ciudad.','level':'A2','category':'modo'},
  {'spanish':'claramente','russian':'ясно / чётко','example':'Explicame claramente el problema.','level':'A2','category':'modo'},
  {'spanish':'facilmente','russian':'легко','example':'Aprendes facilmente los idiomas.','level':'A2','category':'modo'},
  {'spanish':'correctamente','russian':'правильно','example':'Pronuncia las palabras correctamente.','level':'A2','category':'modo'},
  {'spanish':'perfectamente','russian':'отлично / идеально','example':'Habla ingles perfectamente.','level':'A2','category':'modo'},
  {'spanish':'especialmente','russian':'особенно','example':'Me gusta el verano, especialmente agosto.','level':'B1','category':'modo'},
  {'spanish':'simplemente','russian':'просто','example':'Es simplemente increible.','level':'B1','category':'modo'},
  {'spanish':'absolutamente','russian':'абсолютно','example':'Tienes absolutamente razon.','level':'B1','category':'modo'},
  {'spanish':'exactamente','russian':'именно / точно','example':'Eso es exactamente lo que necesito.','level':'B1','category':'modo'},
  {'spanish':'aproximadamente','russian':'приблизительно','example':'Tardara aproximadamente dos horas.','level':'B1','category':'modo'},
  {'spanish':'principalmente','russian':'главным образом','example':'Trabajo principalmente desde casa.','level':'B1','category':'modo'},
  {'spanish':'muy','russian':'очень','example':'Estoy muy cansado.','level':'A1','category':'cantidad'},
  {'spanish':'bastante','russian':'довольно / достаточно','example':'Es bastante dificil.','level':'A1','category':'cantidad'},
  {'spanish':'poco','russian':'немного / мало','example':'Habla un poco de ingles.','level':'A1','category':'cantidad'},
  {'spanish':'mucho','russian':'много','example':'Trabaja mucho.','level':'A1','category':'cantidad'},
  {'spanish':'demasiado','russian':'слишком','example':'Duermes demasiado.','level':'A2','category':'cantidad'},
  {'spanish':'suficiente','russian':'достаточно','example':'Has dormido suficiente?','level':'A2','category':'cantidad'},
  {'spanish':'casi','russian':'почти','example':'Casi llegue tarde.','level':'A2','category':'cantidad'},
  {'spanish':'apenas','russian':'едва / почти нет','example':'Apenas tengo tiempo libre.','level':'B1','category':'cantidad'},
  {'spanish':'totalmente','russian':'полностью / совсем','example':'Estoy totalmente de acuerdo.','level':'B1','category':'cantidad'},
  {'spanish':'parcialmente','russian':'частично','example':'Estoy parcialmente de acuerdo.','level':'B1','category':'cantidad'},
]

# ПРЕДЛОГИ И СОЮЗЫ (+55) — новый раздел
new_prepositions = [
  {'spanish':'a','russian':'в, к, на (направление)','example':'Voy a Madrid manana.','level':'A1','category':'preposicion'},
  {'spanish':'de','russian':'из, от, о (принадлежность)','example':'Soy de Rusia.','level':'A1','category':'preposicion'},
  {'spanish':'en','russian':'в, на (место / время)','example':'Estoy en casa.','level':'A1','category':'preposicion'},
  {'spanish':'con','russian':'с (вместе)','example':'Voy al cine con mis amigos.','level':'A1','category':'preposicion'},
  {'spanish':'sin','russian':'без','example':'No puedo vivir sin cafe.','level':'A1','category':'preposicion'},
  {'spanish':'por','russian':'за, по, из-за, через','example':'Gracias por tu ayuda.','level':'A1','category':'preposicion'},
  {'spanish':'para','russian':'для, чтобы','example':'Este regalo es para ti.','level':'A1','category':'preposicion'},
  {'spanish':'sobre','russian':'о, над, на (поверхности)','example':'Hablamos sobre el proyecto.','level':'A1','category':'preposicion'},
  {'spanish':'entre','russian':'между','example':'Hay un parque entre los dos edificios.','level':'A2','category':'preposicion'},
  {'spanish':'desde','russian':'с (момента), из (места)','example':'Trabajo aqui desde enero.','level':'A2','category':'preposicion'},
  {'spanish':'hasta','russian':'до (места / времени)','example':'Trabajo hasta las seis.','level':'A2','category':'preposicion'},
  {'spanish':'hacia','russian':'к, по направлению к','example':'Caminamos hacia el parque.','level':'A2','category':'preposicion'},
  {'spanish':'durante','russian':'во время / в течение','example':'Durante el verano viajo mucho.','level':'A2','category':'preposicion'},
  {'spanish':'contra','russian':'против','example':'Juegan contra el equipo local.','level':'B1','category':'preposicion'},
  {'spanish':'segun','russian':'по, согласно','example':'Segun el medico, necesito descansar.','level':'B1','category':'preposicion'},
  {'spanish':'a pesar de','russian':'несмотря на','example':'A pesar del frio, salimos.','level':'B1','category':'preposicion'},
  {'spanish':'ademas de','russian':'помимо / кроме','example':'Ademas de espanol, habla frances.','level':'B1','category':'preposicion'},
  {'spanish':'en vez de','russian':'вместо','example':'En vez de quejarte, actua.','level':'B1','category':'preposicion'},
  {'spanish':'a traves de','russian':'через / сквозь','example':'Aprendi a traves de videos.','level':'B1','category':'preposicion'},
  {'spanish':'acerca de','russian':'о, насчёт','example':'Sabes algo acerca de este tema?','level':'B1','category':'preposicion'},
  {'spanish':'dentro de','russian':'внутри / через (время)','example':'El examen es dentro de una hora.','level':'A2','category':'preposicion'},
  {'spanish':'fuera de','russian':'вне / за пределами','example':'Vivo fuera de la ciudad.','level':'A2','category':'preposicion'},
  {'spanish':'delante de','russian':'перед (пространство)','example':'El coche esta delante de la casa.','level':'A2','category':'preposicion'},
  {'spanish':'detras de','russian':'позади / за','example':'El jardin esta detras del edificio.','level':'A2','category':'preposicion'},
  {'spanish':'encima de','russian':'над, поверх','example':'El libro esta encima de la mesa.','level':'A2','category':'preposicion'},
  {'spanish':'debajo de','russian':'под','example':'El gato esta debajo de la cama.','level':'A2','category':'preposicion'},
  {'spanish':'al lado de','russian':'рядом с','example':'La farmacia esta al lado del banco.','level':'A2','category':'preposicion'},
  {'spanish':'cerca de','russian':'близко от / рядом с','example':'Vivo cerca de la estacion.','level':'A2','category':'preposicion'},
  {'spanish':'lejos de','russian':'далеко от','example':'El aeropuerto esta lejos del centro.','level':'A2','category':'preposicion'},
  {'spanish':'y','russian':'и','example':'Habla espanol y frances.','level':'A1','category':'conjuncion'},
  {'spanish':'o','russian':'или','example':'Quieres te o cafe?','level':'A1','category':'conjuncion'},
  {'spanish':'pero','russian':'но','example':'Me gusta, pero es muy caro.','level':'A1','category':'conjuncion'},
  {'spanish':'porque','russian':'потому что','example':'No fui porque estaba enfermo.','level':'A1','category':'conjuncion'},
  {'spanish':'que','russian':'что / который','example':'Creo que tienes razon.','level':'A1','category':'conjuncion'},
  {'spanish':'si','russian':'если','example':'Si estudias, aprobaras.','level':'A1','category':'conjuncion'},
  {'spanish':'cuando','russian':'когда','example':'Llamame cuando llegues.','level':'A1','category':'conjuncion'},
  {'spanish':'aunque','russian':'хотя / несмотря на то что','example':'Aunque llueve, salgo a correr.','level':'A2','category':'conjuncion'},
  {'spanish':'como','russian':'как / поскольку','example':'Como no habia taxi, fui caminando.','level':'A2','category':'conjuncion'},
  {'spanish':'sin embargo','russian':'однако / тем не менее','example':'Es caro; sin embargo, vale la pena.','level':'B1','category':'conjuncion'},
  {'spanish':'por lo tanto','russian':'следовательно / поэтому','example':'Llegue tarde; por lo tanto, me disculpe.','level':'B1','category':'conjuncion'},
  {'spanish':'es decir','russian':'то есть / иными словами','example':'Es bilingue, es decir, habla dos idiomas.','level':'B1','category':'conjuncion'},
  {'spanish':'ademas','russian':'кроме того / также','example':'Habla ingles y, ademas, frances.','level':'B1','category':'conjuncion'},
  {'spanish':'por eso','russian':'поэтому / по этой причине','example':'Estaba cansado; por eso me dormi.','level':'A2','category':'conjuncion'},
  {'spanish':'por ejemplo','russian':'например','example':'Me gustan los deportes, por ejemplo el futbol.','level':'A2','category':'conjuncion'},
  {'spanish':'mientras','russian':'пока / тогда как','example':'Cocina mientras escucha musica.','level':'A2','category':'conjuncion'},
  {'spanish':'para que','russian':'для того чтобы','example':'Te lo digo para que lo sepas.','level':'B1','category':'conjuncion'},
  {'spanish':'ya que','russian':'поскольку / раз уж','example':'Ya que estas aqui, ayudame.','level':'B1','category':'conjuncion'},
  {'spanish':'tan pronto como','russian':'как только','example':'Llamame tan pronto como llegues.','level':'B1','category':'conjuncion'},
  {'spanish':'a menos que','russian':'если только не','example':'Ire a menos que llueva.','level':'B1','category':'conjuncion'},
  {'spanish':'siempre que','russian':'при условии что / всякий раз когда','example':'Te ayudo siempre que me lo pidas.','level':'B1','category':'conjuncion'},
  {'spanish':'no obstante','russian':'тем не менее','example':'No obstante, seguimos adelante.','level':'B2','category':'conjuncion'},
  {'spanish':'debido a que','russian':'вследствие того что','example':'No pude ir debido a que llovia.','level':'B2','category':'conjuncion'},
  {'spanish':'con tal de que','russian':'при условии что / лишь бы','example':'Iria con tal de que me inviten.','level':'B2','category':'conjuncion'},
  {'spanish':'a fin de que','russian':'с тем чтобы','example':'Lo explico a fin de que comprendas.','level':'B2','category':'conjuncion'},
]

# Читаем и обновляем JSON
with open('app/src/main/assets/spanish_vocab.json', encoding='utf-8') as f:
    data = json.load(f)

data['verbs'].extend(new_verbs)
data['nouns'].extend(new_nouns)
data['adjectives'].extend(new_adjectives)
data['adverbs'] = new_adverbs
data['prepositions'] = new_prepositions

total = sum(len(v) for v in data.values())
print('ИТОГО слов в JSON:')
for k,v in data.items():
    print(f'  {k}: {len(v)}')
print(f'  ВСЕГО: {total}')

with open('app/src/main/assets/spanish_vocab.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print('JSON успешно обновлён!')
