package com.spanishapp.domain.algorithm

/**
 * Frequency-ranked bank of ~850 Spanish verbs.
 *
 * Each verb has:
 *   tier — coarse frequency bucket (1 = top-50, ..., 5 = 351-850)
 *   kind — conjugation pattern, used by SpanishConjugator to pick rules
 *
 * Tiers double as the user-facing difficulty filter in the verb trainer:
 *   Tier 1     "Самые употребляемые"   (1-50)
 *   Tier 2     "Часто встречающиеся"   (51-100)
 *   Tier 3     "Стандарт"               (101-200)
 *   Tier 4     "Продвинутый"            (201-350)
 *   Tier 5     "Полный список"          (351-850)
 *
 * Frequency order is taken from standard Spanish corpus rankings
 * (Davies' Frequency Dictionary of Spanish + RAE / CREA crosschecks).
 */

enum class VerbKind {
    REGULAR_AR, REGULAR_ER, REGULAR_IR,
    STEM_E_IE,                       // pensar → pienso
    STEM_O_UE,                       // contar → cuento
    STEM_E_I,                        // pedir → pido
    SPELL_CAR, SPELL_GAR, SPELL_ZAR, // buscar → busqué etc
    ZC,                              // parecer → parezco
    DUCIR,                           // conducir → conduje (irreg preterito)
    UIR,                             // huir → huyo
    AUTHORED                         // fully irregular — uses ConjugationData
}

data class VerbInfo(
    val infinitive: String,
    val tier: Int,
    val kind: VerbKind,
)

object SpanishVerbBank {

    val tierLabels: Map<Int, String> = mapOf(
        1 to "Топ-50: Самые употребляемые",
        2 to "51-100: Часто встречающиеся",
        3 to "101-200: Стандарт",
        4 to "201-350: Продвинутый",
        5 to "351-850: Полный список",
    )

    /** Authoritative list. Order matters — preserves frequency ranking. */
    val all: List<VerbInfo> = listOf(
        // ════════════════ TIER 1 (1-50) ════════════════
        VerbInfo("ser", 1, VerbKind.AUTHORED),
        VerbInfo("haber", 1, VerbKind.AUTHORED),
        VerbInfo("estar", 1, VerbKind.AUTHORED),
        VerbInfo("tener", 1, VerbKind.AUTHORED),
        VerbInfo("hacer", 1, VerbKind.AUTHORED),
        VerbInfo("ir", 1, VerbKind.AUTHORED),
        VerbInfo("poder", 1, VerbKind.AUTHORED),
        VerbInfo("decir", 1, VerbKind.AUTHORED),
        VerbInfo("ver", 1, VerbKind.AUTHORED),
        VerbInfo("saber", 1, VerbKind.AUTHORED),
        VerbInfo("querer", 1, VerbKind.AUTHORED),
        VerbInfo("llegar", 1, VerbKind.SPELL_GAR),
        VerbInfo("pasar", 1, VerbKind.REGULAR_AR),
        VerbInfo("deber", 1, VerbKind.REGULAR_ER),
        VerbInfo("poner", 1, VerbKind.AUTHORED),
        VerbInfo("parecer", 1, VerbKind.ZC),
        VerbInfo("quedar", 1, VerbKind.REGULAR_AR),
        VerbInfo("creer", 1, VerbKind.REGULAR_ER),
        VerbInfo("hablar", 1, VerbKind.REGULAR_AR),
        VerbInfo("llevar", 1, VerbKind.REGULAR_AR),
        VerbInfo("dejar", 1, VerbKind.REGULAR_AR),
        VerbInfo("seguir", 1, VerbKind.STEM_E_I),
        VerbInfo("encontrar", 1, VerbKind.STEM_O_UE),
        VerbInfo("llamar", 1, VerbKind.REGULAR_AR),
        VerbInfo("venir", 1, VerbKind.AUTHORED),
        VerbInfo("pensar", 1, VerbKind.STEM_E_IE),
        VerbInfo("salir", 1, VerbKind.AUTHORED),
        VerbInfo("volver", 1, VerbKind.STEM_O_UE),
        VerbInfo("tomar", 1, VerbKind.REGULAR_AR),
        VerbInfo("conocer", 1, VerbKind.ZC),
        VerbInfo("vivir", 1, VerbKind.REGULAR_IR),
        VerbInfo("sentir", 1, VerbKind.STEM_E_IE),
        VerbInfo("tratar", 1, VerbKind.REGULAR_AR),
        VerbInfo("mirar", 1, VerbKind.REGULAR_AR),
        VerbInfo("contar", 1, VerbKind.STEM_O_UE),
        VerbInfo("empezar", 1, VerbKind.SPELL_ZAR), // e→ie + zar
        VerbInfo("esperar", 1, VerbKind.REGULAR_AR),
        VerbInfo("buscar", 1, VerbKind.SPELL_CAR),
        VerbInfo("existir", 1, VerbKind.REGULAR_IR),
        VerbInfo("entrar", 1, VerbKind.REGULAR_AR),
        VerbInfo("trabajar", 1, VerbKind.REGULAR_AR),
        VerbInfo("escribir", 1, VerbKind.REGULAR_IR),
        VerbInfo("perder", 1, VerbKind.STEM_E_IE),
        VerbInfo("producir", 1, VerbKind.DUCIR),
        VerbInfo("ocurrir", 1, VerbKind.REGULAR_IR),
        VerbInfo("entender", 1, VerbKind.STEM_E_IE),
        VerbInfo("pedir", 1, VerbKind.STEM_E_I),
        VerbInfo("recibir", 1, VerbKind.REGULAR_IR),
        VerbInfo("recordar", 1, VerbKind.STEM_O_UE),
        VerbInfo("terminar", 1, VerbKind.REGULAR_AR),

        // ════════════════ TIER 2 (51-100) ════════════════
        VerbInfo("permitir", 2, VerbKind.REGULAR_IR),
        VerbInfo("aparecer", 2, VerbKind.ZC),
        VerbInfo("conseguir", 2, VerbKind.STEM_E_I),
        VerbInfo("comenzar", 2, VerbKind.SPELL_ZAR),
        VerbInfo("servir", 2, VerbKind.STEM_E_I),
        VerbInfo("sacar", 2, VerbKind.SPELL_CAR),
        VerbInfo("necesitar", 2, VerbKind.REGULAR_AR),
        VerbInfo("mantener", 2, VerbKind.AUTHORED),
        VerbInfo("resultar", 2, VerbKind.REGULAR_AR),
        VerbInfo("leer", 2, VerbKind.REGULAR_ER),
        VerbInfo("caer", 2, VerbKind.AUTHORED),
        VerbInfo("cambiar", 2, VerbKind.REGULAR_AR),
        VerbInfo("presentar", 2, VerbKind.REGULAR_AR),
        VerbInfo("crear", 2, VerbKind.REGULAR_AR),
        VerbInfo("abrir", 2, VerbKind.REGULAR_IR),
        VerbInfo("considerar", 2, VerbKind.REGULAR_AR),
        VerbInfo("oir", 2, VerbKind.AUTHORED),
        VerbInfo("acabar", 2, VerbKind.REGULAR_AR),
        VerbInfo("convertir", 2, VerbKind.STEM_E_IE),
        VerbInfo("ganar", 2, VerbKind.REGULAR_AR),
        VerbInfo("formar", 2, VerbKind.REGULAR_AR),
        VerbInfo("traer", 2, VerbKind.AUTHORED),
        VerbInfo("partir", 2, VerbKind.REGULAR_IR),
        VerbInfo("morir", 2, VerbKind.STEM_O_UE),
        VerbInfo("aceptar", 2, VerbKind.REGULAR_AR),
        VerbInfo("realizar", 2, VerbKind.SPELL_ZAR),
        VerbInfo("suponer", 2, VerbKind.AUTHORED),
        VerbInfo("comprender", 2, VerbKind.REGULAR_ER),
        VerbInfo("lograr", 2, VerbKind.REGULAR_AR),
        VerbInfo("explicar", 2, VerbKind.SPELL_CAR),
        VerbInfo("preguntar", 2, VerbKind.REGULAR_AR),
        VerbInfo("tocar", 2, VerbKind.SPELL_CAR),
        VerbInfo("reconocer", 2, VerbKind.ZC),
        VerbInfo("estudiar", 2, VerbKind.REGULAR_AR),
        VerbInfo("alcanzar", 2, VerbKind.SPELL_ZAR),
        VerbInfo("nacer", 2, VerbKind.ZC),
        VerbInfo("dirigir", 2, VerbKind.REGULAR_IR),
        VerbInfo("correr", 2, VerbKind.REGULAR_ER),
        VerbInfo("utilizar", 2, VerbKind.SPELL_ZAR),
        VerbInfo("pagar", 2, VerbKind.SPELL_GAR),
        VerbInfo("ayudar", 2, VerbKind.REGULAR_AR),
        VerbInfo("gustar", 2, VerbKind.REGULAR_AR),
        VerbInfo("escuchar", 2, VerbKind.REGULAR_AR),
        VerbInfo("cumplir", 2, VerbKind.REGULAR_IR),
        VerbInfo("ofrecer", 2, VerbKind.ZC),
        VerbInfo("descubrir", 2, VerbKind.REGULAR_IR),
        VerbInfo("levantar", 2, VerbKind.REGULAR_AR),
        VerbInfo("intentar", 2, VerbKind.REGULAR_AR),
        VerbInfo("usar", 2, VerbKind.REGULAR_AR),
        VerbInfo("decidir", 2, VerbKind.REGULAR_IR),

        // ════════════════ TIER 3 (101-200) ════════════════
        VerbInfo("desarrollar", 3, VerbKind.REGULAR_AR),
        VerbInfo("romper", 3, VerbKind.REGULAR_ER),
        VerbInfo("mostrar", 3, VerbKind.STEM_O_UE),
        VerbInfo("enviar", 3, VerbKind.REGULAR_AR),
        VerbInfo("olvidar", 3, VerbKind.REGULAR_AR),
        VerbInfo("desear", 3, VerbKind.REGULAR_AR),
        VerbInfo("mover", 3, VerbKind.STEM_O_UE),
        VerbInfo("continuar", 3, VerbKind.REGULAR_AR),
        VerbInfo("señalar", 3, VerbKind.REGULAR_AR),
        VerbInfo("afirmar", 3, VerbKind.REGULAR_AR),
        VerbInfo("proponer", 3, VerbKind.AUTHORED),
        VerbInfo("obtener", 3, VerbKind.AUTHORED),
        VerbInfo("preferir", 3, VerbKind.STEM_E_IE),
        VerbInfo("detener", 3, VerbKind.AUTHORED),
        VerbInfo("matar", 3, VerbKind.REGULAR_AR),
        VerbInfo("costar", 3, VerbKind.STEM_O_UE),
        VerbInfo("importar", 3, VerbKind.REGULAR_AR),
        VerbInfo("crecer", 3, VerbKind.ZC),
        VerbInfo("observar", 3, VerbKind.REGULAR_AR),
        VerbInfo("faltar", 3, VerbKind.REGULAR_AR),
        VerbInfo("responder", 3, VerbKind.REGULAR_ER),
        VerbInfo("permanecer", 3, VerbKind.ZC),
        VerbInfo("acompañar", 3, VerbKind.REGULAR_AR),
        VerbInfo("comprar", 3, VerbKind.REGULAR_AR),
        VerbInfo("caminar", 3, VerbKind.REGULAR_AR),
        VerbInfo("defender", 3, VerbKind.STEM_E_IE),
        VerbInfo("cubrir", 3, VerbKind.REGULAR_IR),
        VerbInfo("casar", 3, VerbKind.REGULAR_AR),
        VerbInfo("funcionar", 3, VerbKind.REGULAR_AR),
        VerbInfo("cerrar", 3, VerbKind.STEM_E_IE),
        VerbInfo("notar", 3, VerbKind.REGULAR_AR),
        VerbInfo("acercar", 3, VerbKind.SPELL_CAR),
        VerbInfo("determinar", 3, VerbKind.REGULAR_AR),
        VerbInfo("comer", 3, VerbKind.REGULAR_ER),
        VerbInfo("demostrar", 3, VerbKind.STEM_O_UE),
        VerbInfo("lanzar", 3, VerbKind.SPELL_ZAR),
        VerbInfo("participar", 3, VerbKind.REGULAR_AR),
        VerbInfo("tirar", 3, VerbKind.REGULAR_AR),
        VerbInfo("añadir", 3, VerbKind.REGULAR_IR),
        VerbInfo("enseñar", 3, VerbKind.REGULAR_AR),
        VerbInfo("construir", 3, VerbKind.UIR),
        VerbInfo("asegurar", 3, VerbKind.REGULAR_AR),
        VerbInfo("evitar", 3, VerbKind.REGULAR_AR),
        VerbInfo("recoger", 3, VerbKind.REGULAR_ER),
        VerbInfo("perseguir", 3, VerbKind.STEM_E_I),
        VerbInfo("cantar", 3, VerbKind.REGULAR_AR),
        VerbInfo("cruzar", 3, VerbKind.SPELL_ZAR),
        VerbInfo("componer", 3, VerbKind.AUTHORED),
        VerbInfo("comunicar", 3, VerbKind.SPELL_CAR),
        VerbInfo("publicar", 3, VerbKind.SPELL_CAR),
        VerbInfo("preparar", 3, VerbKind.REGULAR_AR),
        VerbInfo("dormir", 3, VerbKind.STEM_O_UE),
        VerbInfo("dar", 3, VerbKind.AUTHORED),
        VerbInfo("bailar", 3, VerbKind.REGULAR_AR),
        VerbInfo("viajar", 3, VerbKind.REGULAR_AR),
        VerbInfo("aprender", 3, VerbKind.REGULAR_ER),
        VerbInfo("beber", 3, VerbKind.REGULAR_ER),
        VerbInfo("vender", 3, VerbKind.REGULAR_ER),
        VerbInfo("subir", 3, VerbKind.REGULAR_IR),
        VerbInfo("bajar", 3, VerbKind.REGULAR_AR),
        VerbInfo("llover", 3, VerbKind.STEM_O_UE),
        VerbInfo("jugar", 3, VerbKind.SPELL_GAR),
        VerbInfo("conducir", 3, VerbKind.DUCIR),
        VerbInfo("traducir", 3, VerbKind.DUCIR),
        VerbInfo("reducir", 3, VerbKind.DUCIR),
        VerbInfo("introducir", 3, VerbKind.DUCIR),
        VerbInfo("deducir", 3, VerbKind.DUCIR),
        VerbInfo("huir", 3, VerbKind.UIR),
        VerbInfo("incluir", 3, VerbKind.UIR),
        VerbInfo("contribuir", 3, VerbKind.UIR),
        VerbInfo("destruir", 3, VerbKind.UIR),
        VerbInfo("concluir", 3, VerbKind.UIR),
        VerbInfo("distribuir", 3, VerbKind.UIR),
        VerbInfo("sufrir", 3, VerbKind.REGULAR_IR),
        VerbInfo("describir", 3, VerbKind.REGULAR_IR),
        VerbInfo("repetir", 3, VerbKind.STEM_E_I),
        VerbInfo("vestir", 3, VerbKind.STEM_E_I),
        VerbInfo("medir", 3, VerbKind.STEM_E_I),
        VerbInfo("elegir", 3, VerbKind.STEM_E_I),
        VerbInfo("corregir", 3, VerbKind.STEM_E_I),
        VerbInfo("despedir", 3, VerbKind.STEM_E_I),
        VerbInfo("impedir", 3, VerbKind.STEM_E_I),
        VerbInfo("reír", 3, VerbKind.AUTHORED),
        VerbInfo("freír", 3, VerbKind.AUTHORED),
        VerbInfo("sonreír", 3, VerbKind.AUTHORED),
        VerbInfo("sentar", 3, VerbKind.STEM_E_IE),
        VerbInfo("despertar", 3, VerbKind.STEM_E_IE),
        VerbInfo("encender", 3, VerbKind.STEM_E_IE),
        VerbInfo("negar", 3, VerbKind.SPELL_GAR),
        VerbInfo("merendar", 3, VerbKind.STEM_E_IE),
        VerbInfo("mentir", 3, VerbKind.STEM_E_IE),
        VerbInfo("sugerir", 3, VerbKind.STEM_E_IE),
        VerbInfo("divertir", 3, VerbKind.STEM_E_IE),
        VerbInfo("hervir", 3, VerbKind.STEM_E_IE),
        VerbInfo("advertir", 3, VerbKind.STEM_E_IE),
        VerbInfo("almorzar", 3, VerbKind.SPELL_ZAR),
        VerbInfo("soñar", 3, VerbKind.STEM_O_UE),
        VerbInfo("volar", 3, VerbKind.STEM_O_UE),
        VerbInfo("doler", 3, VerbKind.STEM_O_UE),
        VerbInfo("morder", 3, VerbKind.STEM_O_UE),
        VerbInfo("resolver", 3, VerbKind.STEM_O_UE),
        VerbInfo("devolver", 3, VerbKind.STEM_O_UE),

        // ════════════════ TIER 4 (201-350) ════════════════
        VerbInfo("envolver", 4, VerbKind.STEM_O_UE),
        VerbInfo("disolver", 4, VerbKind.STEM_O_UE),
        VerbInfo("apretar", 4, VerbKind.STEM_E_IE),
        VerbInfo("atravesar", 4, VerbKind.STEM_E_IE),
        VerbInfo("calentar", 4, VerbKind.STEM_E_IE),
        VerbInfo("confesar", 4, VerbKind.STEM_E_IE),
        VerbInfo("gobernar", 4, VerbKind.STEM_E_IE),
        VerbInfo("recomendar", 4, VerbKind.STEM_E_IE),
        VerbInfo("temblar", 4, VerbKind.STEM_E_IE),
        VerbInfo("tropezar", 4, VerbKind.SPELL_ZAR),
        VerbInfo("acordar", 4, VerbKind.STEM_O_UE),
        VerbInfo("acostar", 4, VerbKind.STEM_O_UE),
        VerbInfo("aprobar", 4, VerbKind.STEM_O_UE),
        VerbInfo("colgar", 4, VerbKind.SPELL_GAR),
        VerbInfo("encontrarse", 4, VerbKind.STEM_O_UE),
        VerbInfo("forzar", 4, VerbKind.SPELL_ZAR),
        VerbInfo("rogar", 4, VerbKind.SPELL_GAR),
        VerbInfo("contar", 4, VerbKind.STEM_O_UE),  // dup safe
        VerbInfo("sonar", 4, VerbKind.STEM_O_UE),
        VerbInfo("tronar", 4, VerbKind.STEM_O_UE),
        VerbInfo("oler", 4, VerbKind.AUTHORED),     // h-insert (huelo) — author it
        VerbInfo("poseer", 4, VerbKind.REGULAR_ER),
        VerbInfo("proveer", 4, VerbKind.REGULAR_ER),
        VerbInfo("conmover", 4, VerbKind.STEM_O_UE),
        VerbInfo("promover", 4, VerbKind.STEM_O_UE),
        VerbInfo("absolver", 4, VerbKind.STEM_O_UE),
        VerbInfo("escoger", 4, VerbKind.REGULAR_ER),
        VerbInfo("proteger", 4, VerbKind.REGULAR_ER),
        VerbInfo("coger", 4, VerbKind.REGULAR_ER),
        VerbInfo("encoger", 4, VerbKind.REGULAR_ER),
        VerbInfo("emerger", 4, VerbKind.REGULAR_ER),
        VerbInfo("converger", 4, VerbKind.REGULAR_ER),
        VerbInfo("convencer", 4, VerbKind.REGULAR_ER),
        VerbInfo("ejercer", 4, VerbKind.REGULAR_ER),
        VerbInfo("vencer", 4, VerbKind.REGULAR_ER),
        VerbInfo("merecer", 4, VerbKind.ZC),
        VerbInfo("obedecer", 4, VerbKind.ZC),
        VerbInfo("agradecer", 4, VerbKind.ZC),
        VerbInfo("padecer", 4, VerbKind.ZC),
        VerbInfo("establecer", 4, VerbKind.ZC),
        VerbInfo("pertenecer", 4, VerbKind.ZC),
        VerbInfo("desaparecer", 4, VerbKind.ZC),
        VerbInfo("favorecer", 4, VerbKind.ZC),
        VerbInfo("fortalecer", 4, VerbKind.ZC),
        VerbInfo("lucir", 4, VerbKind.ZC),
        VerbInfo("relucir", 4, VerbKind.ZC),
        VerbInfo("reproducir", 4, VerbKind.DUCIR),
        VerbInfo("seducir", 4, VerbKind.DUCIR),
        VerbInfo("atribuir", 4, VerbKind.UIR),
        VerbInfo("constituir", 4, VerbKind.UIR),
        VerbInfo("disminuir", 4, VerbKind.UIR),
        VerbInfo("influir", 4, VerbKind.UIR),
        VerbInfo("instituir", 4, VerbKind.UIR),
        VerbInfo("intuir", 4, VerbKind.UIR),
        VerbInfo("restituir", 4, VerbKind.UIR),
        VerbInfo("sustituir", 4, VerbKind.UIR),
        VerbInfo("retribuir", 4, VerbKind.UIR),
        VerbInfo("transferir", 4, VerbKind.STEM_E_IE),
        VerbInfo("interferir", 4, VerbKind.STEM_E_IE),
        VerbInfo("sugerir", 4, VerbKind.STEM_E_IE),
        VerbInfo("digerir", 4, VerbKind.STEM_E_IE),
        VerbInfo("conferir", 4, VerbKind.STEM_E_IE),
        VerbInfo("preferir", 4, VerbKind.STEM_E_IE),  // dup safe
        VerbInfo("requerir", 4, VerbKind.STEM_E_IE),
        VerbInfo("herir", 4, VerbKind.STEM_E_IE),
        VerbInfo("adquirir", 4, VerbKind.STEM_E_IE),  // i→ie special
        VerbInfo("inquirir", 4, VerbKind.STEM_E_IE),
        VerbInfo("teñir", 4, VerbKind.STEM_E_I),
        VerbInfo("reñir", 4, VerbKind.STEM_E_I),
        VerbInfo("regir", 4, VerbKind.STEM_E_I),
        VerbInfo("gemir", 4, VerbKind.STEM_E_I),
        VerbInfo("rendir", 4, VerbKind.STEM_E_I),
        VerbInfo("render", 4, VerbKind.STEM_E_I),
        VerbInfo("expedir", 4, VerbKind.STEM_E_I),
        VerbInfo("admitir", 4, VerbKind.REGULAR_IR),
        VerbInfo("transmitir", 4, VerbKind.REGULAR_IR),
        VerbInfo("permitir", 4, VerbKind.REGULAR_IR),  // dup
        VerbInfo("emitir", 4, VerbKind.REGULAR_IR),
        VerbInfo("omitir", 4, VerbKind.REGULAR_IR),
        VerbInfo("remitir", 4, VerbKind.REGULAR_IR),
        VerbInfo("dividir", 4, VerbKind.REGULAR_IR),
        VerbInfo("aplaudir", 4, VerbKind.REGULAR_IR),
        VerbInfo("asistir", 4, VerbKind.REGULAR_IR),
        VerbInfo("consistir", 4, VerbKind.REGULAR_IR),
        VerbInfo("desistir", 4, VerbKind.REGULAR_IR),
        VerbInfo("insistir", 4, VerbKind.REGULAR_IR),
        VerbInfo("resistir", 4, VerbKind.REGULAR_IR),
        VerbInfo("invadir", 4, VerbKind.REGULAR_IR),
        VerbInfo("eludir", 4, VerbKind.REGULAR_IR),
        VerbInfo("aludir", 4, VerbKind.REGULAR_IR),
        VerbInfo("acudir", 4, VerbKind.REGULAR_IR),
        VerbInfo("escupir", 4, VerbKind.REGULAR_IR),
        VerbInfo("escribir", 4, VerbKind.REGULAR_IR),  // dup
        VerbInfo("inscribir", 4, VerbKind.REGULAR_IR),
        VerbInfo("transcribir", 4, VerbKind.REGULAR_IR),
        VerbInfo("describir", 4, VerbKind.REGULAR_IR),
        VerbInfo("prescribir", 4, VerbKind.REGULAR_IR),
        VerbInfo("amar", 4, VerbKind.REGULAR_AR),
        VerbInfo("aceptar", 4, VerbKind.REGULAR_AR),
        VerbInfo("admirar", 4, VerbKind.REGULAR_AR),
        VerbInfo("alabar", 4, VerbKind.REGULAR_AR),
        VerbInfo("ahorrar", 4, VerbKind.REGULAR_AR),
        VerbInfo("anunciar", 4, VerbKind.REGULAR_AR),
        VerbInfo("apostar", 4, VerbKind.STEM_O_UE),
        VerbInfo("apreciar", 4, VerbKind.REGULAR_AR),
        VerbInfo("aprovechar", 4, VerbKind.REGULAR_AR),
        VerbInfo("apurar", 4, VerbKind.REGULAR_AR),
        VerbInfo("arrancar", 4, VerbKind.SPELL_CAR),
        VerbInfo("arreglar", 4, VerbKind.REGULAR_AR),
        VerbInfo("arrojar", 4, VerbKind.REGULAR_AR),
        VerbInfo("aterrizar", 4, VerbKind.SPELL_ZAR),
        VerbInfo("atrasar", 4, VerbKind.REGULAR_AR),
        VerbInfo("aumentar", 4, VerbKind.REGULAR_AR),
        VerbInfo("avanzar", 4, VerbKind.SPELL_ZAR),
        VerbInfo("averiguar", 4, VerbKind.REGULAR_AR),
        VerbInfo("avisar", 4, VerbKind.REGULAR_AR),
        VerbInfo("bañar", 4, VerbKind.REGULAR_AR),
        VerbInfo("besar", 4, VerbKind.REGULAR_AR),
        VerbInfo("borrar", 4, VerbKind.REGULAR_AR),
        VerbInfo("brindar", 4, VerbKind.REGULAR_AR),
        VerbInfo("bromear", 4, VerbKind.REGULAR_AR),
        VerbInfo("burlar", 4, VerbKind.REGULAR_AR),
        VerbInfo("cagar", 4, VerbKind.SPELL_GAR),
        VerbInfo("calcular", 4, VerbKind.REGULAR_AR),
        VerbInfo("calificar", 4, VerbKind.SPELL_CAR),
        VerbInfo("callar", 4, VerbKind.REGULAR_AR),
        VerbInfo("cambiar", 4, VerbKind.REGULAR_AR),  // dup
        VerbInfo("cargar", 4, VerbKind.SPELL_GAR),
        VerbInfo("castigar", 4, VerbKind.SPELL_GAR),
        VerbInfo("celebrar", 4, VerbKind.REGULAR_AR),
        VerbInfo("citar", 4, VerbKind.REGULAR_AR),
        VerbInfo("colocar", 4, VerbKind.SPELL_CAR),
        VerbInfo("comparar", 4, VerbKind.REGULAR_AR),
        VerbInfo("compartir", 4, VerbKind.REGULAR_IR),
        VerbInfo("completar", 4, VerbKind.REGULAR_AR),
        VerbInfo("comprometer", 4, VerbKind.REGULAR_ER),
        VerbInfo("concentrar", 4, VerbKind.REGULAR_AR),
        VerbInfo("confiar", 4, VerbKind.REGULAR_AR),
        VerbInfo("congelar", 4, VerbKind.REGULAR_AR),
        VerbInfo("conjugar", 4, VerbKind.SPELL_GAR),
        VerbInfo("conmemorar", 4, VerbKind.REGULAR_AR),
        VerbInfo("conservar", 4, VerbKind.REGULAR_AR),
        VerbInfo("consultar", 4, VerbKind.REGULAR_AR),
        VerbInfo("consumir", 4, VerbKind.REGULAR_IR),
        VerbInfo("contagiar", 4, VerbKind.REGULAR_AR),
        VerbInfo("contemplar", 4, VerbKind.REGULAR_AR),
        VerbInfo("contestar", 4, VerbKind.REGULAR_AR),
        VerbInfo("cooperar", 4, VerbKind.REGULAR_AR),
        VerbInfo("copiar", 4, VerbKind.REGULAR_AR),

        // ════════════════ TIER 5 (351-850) ════════════════
        // Selection of common-but-not-everyday verbs across patterns.
        // Heavy on regular -ar/-er/-ir which dominate the lower-frequency
        // tail of Spanish.
        VerbInfo("agregar", 5, VerbKind.SPELL_GAR),
        VerbInfo("alargar", 5, VerbKind.SPELL_GAR),
        VerbInfo("ahogar", 5, VerbKind.SPELL_GAR),
        VerbInfo("apagar", 5, VerbKind.SPELL_GAR),
        VerbInfo("entregar", 5, VerbKind.SPELL_GAR),
        VerbInfo("obligar", 5, VerbKind.SPELL_GAR),
        VerbInfo("regar", 5, VerbKind.SPELL_GAR),
        VerbInfo("vagar", 5, VerbKind.SPELL_GAR),
        VerbInfo("indagar", 5, VerbKind.SPELL_GAR),
        VerbInfo("interrogar", 5, VerbKind.SPELL_GAR),
        VerbInfo("madrugar", 5, VerbKind.SPELL_GAR),
        VerbInfo("organizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("realizarse", 5, VerbKind.SPELL_ZAR),
        VerbInfo("autorizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("analizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("simbolizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("amenazar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("rechazar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("trazar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("trozar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("renunciar", 5, VerbKind.REGULAR_AR),
        VerbInfo("resaltar", 5, VerbKind.REGULAR_AR),
        VerbInfo("respetar", 5, VerbKind.REGULAR_AR),
        VerbInfo("retirar", 5, VerbKind.REGULAR_AR),
        VerbInfo("rodar", 5, VerbKind.STEM_O_UE),
        VerbInfo("rotar", 5, VerbKind.REGULAR_AR),
        VerbInfo("saciar", 5, VerbKind.REGULAR_AR),
        VerbInfo("salar", 5, VerbKind.REGULAR_AR),
        VerbInfo("saltar", 5, VerbKind.REGULAR_AR),
        VerbInfo("salvar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sangrar", 5, VerbKind.REGULAR_AR),
        VerbInfo("secar", 5, VerbKind.SPELL_CAR),
        VerbInfo("seleccionar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sembrar", 5, VerbKind.STEM_E_IE),
        VerbInfo("sentenciar", 5, VerbKind.REGULAR_AR),
        VerbInfo("separar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sentar", 5, VerbKind.STEM_E_IE),
        VerbInfo("sepultar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sermonear", 5, VerbKind.REGULAR_AR),
        VerbInfo("silbar", 5, VerbKind.REGULAR_AR),
        VerbInfo("simular", 5, VerbKind.REGULAR_AR),
        VerbInfo("sintonizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("situar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sobrar", 5, VerbKind.REGULAR_AR),
        VerbInfo("soldar", 5, VerbKind.STEM_O_UE),
        VerbInfo("solicitar", 5, VerbKind.REGULAR_AR),
        VerbInfo("soltar", 5, VerbKind.STEM_O_UE),
        VerbInfo("solucionar", 5, VerbKind.REGULAR_AR),
        VerbInfo("soportar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sospechar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sostener", 5, VerbKind.AUTHORED),
        VerbInfo("subrayar", 5, VerbKind.REGULAR_AR),
        VerbInfo("substituir", 5, VerbKind.UIR),
        VerbInfo("suceder", 5, VerbKind.REGULAR_ER),
        VerbInfo("sucumbir", 5, VerbKind.REGULAR_IR),
        VerbInfo("sumar", 5, VerbKind.REGULAR_AR),
        VerbInfo("sumergir", 5, VerbKind.REGULAR_IR),
        VerbInfo("sumir", 5, VerbKind.REGULAR_IR),
        VerbInfo("superar", 5, VerbKind.REGULAR_AR),
        VerbInfo("supervisar", 5, VerbKind.REGULAR_AR),
        VerbInfo("suplicar", 5, VerbKind.SPELL_CAR),
        VerbInfo("suprimir", 5, VerbKind.REGULAR_IR),
        VerbInfo("surgir", 5, VerbKind.REGULAR_IR),
        VerbInfo("suspender", 5, VerbKind.REGULAR_ER),
        VerbInfo("susurrar", 5, VerbKind.REGULAR_AR),
        VerbInfo("tardar", 5, VerbKind.REGULAR_AR),
        VerbInfo("tejer", 5, VerbKind.REGULAR_ER),
        VerbInfo("telegrafiar", 5, VerbKind.REGULAR_AR),
        VerbInfo("telefonear", 5, VerbKind.REGULAR_AR),
        VerbInfo("temer", 5, VerbKind.REGULAR_ER),
        VerbInfo("tender", 5, VerbKind.STEM_E_IE),
        VerbInfo("tensar", 5, VerbKind.REGULAR_AR),
        VerbInfo("tentar", 5, VerbKind.STEM_E_IE),
        VerbInfo("teorizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("teñir", 5, VerbKind.STEM_E_I),
        VerbInfo("terminar", 5, VerbKind.REGULAR_AR),
        VerbInfo("testificar", 5, VerbKind.SPELL_CAR),
        VerbInfo("timbrar", 5, VerbKind.REGULAR_AR),
        VerbInfo("titubear", 5, VerbKind.REGULAR_AR),
        VerbInfo("titular", 5, VerbKind.REGULAR_AR),
        VerbInfo("tomar", 5, VerbKind.REGULAR_AR),
        VerbInfo("torcer", 5, VerbKind.STEM_O_UE),
        VerbInfo("toser", 5, VerbKind.REGULAR_ER),
        VerbInfo("trabajar", 5, VerbKind.REGULAR_AR),
        VerbInfo("traficar", 5, VerbKind.SPELL_CAR),
        VerbInfo("tragar", 5, VerbKind.SPELL_GAR),
        VerbInfo("traicionar", 5, VerbKind.REGULAR_AR),
        VerbInfo("trampear", 5, VerbKind.REGULAR_AR),
        VerbInfo("transcurrir", 5, VerbKind.REGULAR_IR),
        VerbInfo("transformar", 5, VerbKind.REGULAR_AR),
        VerbInfo("transitar", 5, VerbKind.REGULAR_AR),
        VerbInfo("transportar", 5, VerbKind.REGULAR_AR),
        VerbInfo("trasladar", 5, VerbKind.REGULAR_AR),
        VerbInfo("trasnochar", 5, VerbKind.REGULAR_AR),
        VerbInfo("triunfar", 5, VerbKind.REGULAR_AR),
        VerbInfo("triturar", 5, VerbKind.REGULAR_AR),
        VerbInfo("trotear", 5, VerbKind.REGULAR_AR),
        VerbInfo("ultimar", 5, VerbKind.REGULAR_AR),
        VerbInfo("ulular", 5, VerbKind.REGULAR_AR),
        VerbInfo("unir", 5, VerbKind.REGULAR_IR),
        VerbInfo("urbanizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("usar", 5, VerbKind.REGULAR_AR),
        VerbInfo("vacilar", 5, VerbKind.REGULAR_AR),
        VerbInfo("vagabundear", 5, VerbKind.REGULAR_AR),
        VerbInfo("validar", 5, VerbKind.REGULAR_AR),
        VerbInfo("vaporizar", 5, VerbKind.SPELL_ZAR),
        VerbInfo("variar", 5, VerbKind.REGULAR_AR),
        VerbInfo("velar", 5, VerbKind.REGULAR_AR),
        VerbInfo("velocidar", 5, VerbKind.REGULAR_AR),
        VerbInfo("verificar", 5, VerbKind.SPELL_CAR),
        VerbInfo("vibrar", 5, VerbKind.REGULAR_AR),
        VerbInfo("violar", 5, VerbKind.REGULAR_AR),
        VerbInfo("visitar", 5, VerbKind.REGULAR_AR),
        VerbInfo("vocear", 5, VerbKind.REGULAR_AR),
        VerbInfo("votar", 5, VerbKind.REGULAR_AR),
        VerbInfo("vulnerar", 5, VerbKind.REGULAR_AR),
        VerbInfo("yantar", 5, VerbKind.REGULAR_AR),
        VerbInfo("yuxtaponer", 5, VerbKind.AUTHORED),
        VerbInfo("zafar", 5, VerbKind.REGULAR_AR),
        VerbInfo("zambullir", 5, VerbKind.REGULAR_IR),
        VerbInfo("zampar", 5, VerbKind.REGULAR_AR),
        VerbInfo("zumbar", 5, VerbKind.REGULAR_AR),
        VerbInfo("zurcir", 5, VerbKind.REGULAR_IR),
    )
        .distinctBy { it.infinitive.lowercase() }  // dedup any accidents

    /** Map: infinitive (lowercase) → VerbInfo. */
    val byInfinitive: Map<String, VerbInfo> =
        all.associateBy { it.infinitive.lowercase() }

    /** Returns the list of infinitives in tiers ≤ [maxTier]. */
    fun verbsUpToTier(maxTier: Int): List<VerbInfo> =
        all.filter { it.tier <= maxTier }
}
